IMPORT LIBRARIES

In [1]:
import numpy as np
import pandas as pd

READ DATA

In [2]:
data  = pd.read_csv("tweets.csv")
data = data.sample(frac=1).reset_index(drop=True)
data.head()

tweet_id airline_sentiment  airline_sentiment_confidence  \
0  568448023845572608           neutral                        0.6423   
1  567840103122509825          negative                        1.0000   
2  569710305707601920          negative                        1.0000   
3  570028083606122497          positive                        1.0000   
4  569358701317869571          negative                        1.0000   

     negativereason  negativereason_confidence     airline  \
0               NaN                        NaN       Delta   
1  Cancelled Flight                        1.0  US Airways   
2       Late Flight                        1.0  US Airways   
3               NaN                        NaN    American   
4       Late Flight                        1.0   Southwest   

  airline_sentiment_gold             name negativereason_gold  retweet_count  \
0                    NaN         smsuconn                 NaN              0   
1                    NaN   unpredictaylor                 NaN              0   
2                    NaN        EAFiedler                 NaN              0   
3                    NaN          LSlay19                 NaN              0   
4                    NaN  masonsontwiter2                 NaN              0   

                                                text tweet_coord  \
0  @JetBlue yes he and all the princesses. Trying...         NaN   
1  @USAirways UR service is so shitty. Pilot neve...         NaN   
2  @USAirways flight #703 Philly -&gt; Mia? Bwaha...         NaN   
3                        @AmericanAir thanks, me too         NaN   
4  @SouthwestAir yall have me sleeping in the air...         NaN   

               tweet_created              tweet_location  \
0  2015-02-19 08:32:24 -0800              Alexandria, VA   
1  2015-02-17 16:16:45 -0800                         NaN   
2  2015-02-22 20:08:16 -0800                      Philly   
3  2015-02-23 17:11:00 -0800  NC by day, DC by night....   
4  2015-02-21 20:51:07 -0800                         NaN   

                user_timezone  
0  Eastern Time (US & Canada)  
1      Atlantic Time (Canada)  
2  Eastern Time (US & Canada)  
3                       Quito  
4                      Alaska

EXTRACTING LABELS AND TWEETS

In [3]:
reviews = np.array(data['text'])
labels = np.array(data['airline_sentiment'])
reviews

array(['@JetBlue yes he and all the princesses. Trying to get to the #glassslipperchallenge at WDW.',
       "@USAirways UR service is so shitty. Pilot never showed up so we waited hours because another pilot was supposed to come but didn't #Cancelled Flighted",
       '@USAirways flight #703 Philly -&gt; Mia? Bwahahaha! Delayed 5+ hrs, were in the air 30 mins then turned back around. #usairwaysfail',
       ...,
       "@JetBlue Even though this flight #226 didn't have much needed hot beverages 4 us NY-ers, the landing was super smooth 👍👍 😊 #happytweet",
       '@SouthwestAir Thanks. I did go through these motions shortly after my flight yesterday. I wonder how quickly flight attendants are notified.',
       '@United super lame that you charge $8 for tv on an international flight to the US. It isn’t 1997!'],
      dtype=object)

In [4]:
labels

array(['neutral', 'negative', 'negative', ..., 'positive', 'positive',
       'negative'], dtype=object)

CLEARING PUNCTUATIONS , HYPERLINKS , AND NUMBERS

In [5]:
from string import punctuation
def clean(words):
  #  punctuation = '@!"#$%&'\()*+,-./:;<=>?[\\]^_`{|}~'
    nword = []
    for word in words:
        if word[0] not in punctuation and word.find('http')==-1 and any(char.isdigit() for char in word)==False:
            #word = word.replace(punctuation, ' ')
            for pun in punctuation:
                word = word.replace(pun,'')
                word = word.lower()
                word = word.replace(" s "," ")
                
            nword.append(word)
    
    return nword

IMPORT SPACY's ENGLISH 

In [6]:
import spacy
spacy.prefer_gpu()
nlp = spacy.load("en_core_web_sm")

FUNCTION FOR LEMMATIZATION

In [7]:
def lemma(sentence):
    doc = nlp(sentence)
   # print(doc)
    sent = " ".join([token.lemma_ for token in doc if token.is_stop==False])
   # print(sent)
# Extract the lemma for each token and join
    return sent

LEMMATIZING AND CLEANING 

In [8]:

revs = []
for re in reviews:
    #print(re)
    re = lemma(re)
    re = re.split()
    rn = clean(re)
    revs.append(rn)
    #print(rn)
revs

[['yes', 'princess', 'try', 'glassslipperchallenge', 'wdw'],
 ['ur',
  'service',
  'shitty',
  'pilot',
  'show',
  'wait',
  'hour',
  'pilot',
  'suppose',
  'come',
  'cancel',
  'flighted'],
 ['flight',
  'philly',
  'mia',
  'bwahahaha',
  'delay',
  'hrs',
  'air',
  'min',
  'turn',
  'usairwaysfail'],
 ['thanks'],
 ['sleep', 'airport', 'pm', 'tomorrow', 'thank'],
 ['fa', 'ground', 'personnel', 'great', 'job', 'weather', 'blame', 'talk'],
 ['raleigh', 'update', 'southern', 'states', 'advisory'],
 ['bad', 'company', 'fly', 'repeat', 'fly', 'credit', 'delay'],
 ['go',
  'miss',
  'hugely',
  'important',
  'meeting',
  'constant',
  'delay',
  'itscostingmeincome'],
 ['😃', 'cool'],
 ['stay', 'travel', 'ans', 'sleep', 'airport', 'floor'],
 ['expect', 'flight', 'dfw', 'cancel', 'flightled', 'tomorrow', 'afternoon'],
 ['ok', 'hope', 'thy', 'bahamas'],
 ['thank', 'get', 'find', 'airline', 'future'],
 [],
 ['thx', 'follow', 'send', 'dm'],
 ['look', 'well', 'service'],
 ['flight', 'ewr

making an array of all words

In [9]:
all_words = []
for re in revs:
    for word in re:
        all_words.append(word)
        
print(all_words)

['yes', 'princess', 'try', 'glassslipperchallenge', 'wdw', 'ur', 'service', 'shitty', 'pilot', 'show', 'wait', 'hour', 'pilot', 'suppose', 'come', 'cancel', 'flighted', 'flight', 'philly', 'mia', 'bwahahaha', 'delay', 'hrs', 'air', 'min', 'turn', 'usairwaysfail', 'thanks', 'sleep', 'airport', 'pm', 'tomorrow', 'thank', 'fa', 'ground', 'personnel', 'great', 'job', 'weather', 'blame', 'talk', 'raleigh', 'update', 'southern', 'states', 'advisory', 'bad', 'company', 'fly', 'repeat', 'fly', 'credit', 'delay', 'go', 'miss', 'hugely', 'important', 'meeting', 'constant', 'delay', 'itscostingmeincome', '😃', 'cool', 'stay', 'travel', 'ans', 'sleep', 'airport', 'floor', 'expect', 'flight', 'dfw', 'cancel', 'flightled', 'tomorrow', 'afternoon', 'ok', 'hope', 'thy', 'bahamas', 'thank', 'get', 'find', 'airline', 'future', 'thx', 'follow', 'send', 'dm', 'look', 'well', 'service', 'flight', 'ewr', 'stop', 'dallas', 'la', 'need', 'la', 'tonight', 'lmfao', 'flight', 'cheap', 'catch', 'happen', 'locate',

**tokenizing unique words**


In [10]:
from collections import Counter
counts = Counter(all_words)

sorted_counts = sorted(counts,key=counts.get,reverse=True)
word_to_int = {word:ii for ii,word in enumerate(sorted_counts,1)}

sz = len(word_to_int)

coded_revs = []
for review in revs:
    coded_revs.append([word_to_int[word] for word in review])

coded_revs


[[73, 3299, 18, 4547, 4548],
 [273, 4, 1334, 140, 278, 13, 3, 140, 193, 82, 5, 80],
 [1, 358, 553, 4549, 6, 103, 132, 53, 359, 680],
 [489],
 [326, 41, 218, 52, 2],
 [964, 220, 1335, 46, 227, 51, 641, 144],
 [1184, 100, 3300, 3301, 662],
 [29, 228, 11, 1336, 11, 142, 6],
 [24, 38, 2680, 847, 642, 1798, 6, 4550],
 [965, 312],
 [285, 49, 4551, 326, 41, 1008],
 [248, 1, 110, 5, 37, 52, 602],
 [194, 90, 3302, 2008],
 [2, 12, 70, 22, 465],
 [],
 [195, 91, 50, 67],
 [58, 155, 4],
 [1, 210, 178, 229, 412, 16, 412, 111],
 [2296],
 [1, 603, 526],
 [106, 733],
 [17, 23, 1185, 136, 879, 375, 129, 207, 25, 680],
 [82, 266, 4, 4552, 1063, 4553, 1186, 41],
 [267, 604, 777, 7, 30, 1, 6, 5, 37, 879],
 [4554, 21, 754, 3303, 87, 2009, 1799, 289, 1511, 2681, 3303],
 [27, 202, 510, 76, 190, 5, 37],
 [2, 1512, 2682, 1800, 4555, 927, 4556],
 [1513, 75, 282, 14, 1514, 554],
 [3304, 624, 1337, 132, 3, 33, 1, 155, 5, 37],
 [85],
 [4, 279, 2010, 47, 286, 77, 389, 511, 313, 166],
 [481, 116, 150, 57, 32, 18, 44,

In [11]:
print(sz)

9481


ENCODING LABELS

In [12]:
classes=[]
for lab in labels:
    if lab=='positive':
        classes.append([0,0,1])
    elif lab=='neutral':
        classes.append([0,1,0])
    else :
        classes.append([1,0,0])
classes

[[0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [1,

MAX AND MIN LENGTH OF REVIEWS

In [13]:
review_lens = Counter([len(x) for x in coded_revs])
print("Zero-length reviews: {}".format(review_lens[0]))
print("Maximum review length: {}".format(max(review_lens)))

Zero-length reviews: 70
Maximum review length: 43


In [14]:
for i in range(44):
    print(i,review_lens[i])

0 70
1 531
2 659
3 922
4 1019
5 1100
6 1304
7 1344
8 1487
9 1587
10 1517
11 1159
12 880
13 520
14 285
15 133
16 62
17 33
18 14
19 6
20 4
21 0
22 0
23 1
24 0
25 0
26 0
27 1
28 0
29 0
30 1
31 0
32 0
33 0
34 0
35 0
36 0
37 0
38 0
39 0
40 0
41 0
42 0
43 1


REMOVING REVIEWS WITH 0 LENGTH

In [15]:
print('Number of reviews before removing outliers: ', len(coded_revs))

## remove any reviews/labels with zero length from the coded_revs list.

# get indices of any reviews with length 0
non_zero_idx = [ii for ii, review in enumerate(coded_revs) if len(review) != 0]

# remove 0-length reviews and their labels
coded_revs = [coded_revs[ii] for ii in non_zero_idx]
classes = np.array([classes[ii] for ii in non_zero_idx])

print('Number of reviews after removing outliers: ', len(coded_revs))

Number of reviews before removing outliers:  14640
Number of reviews after removing outliers:  14570


FUNTION TO PAD REVIEWS (right)

In [16]:
def pad_features(reviews_ints, seq_length):
    ''' Return features of review_ints, where each review is padded with 0's 
        or truncated to the input seq_length.
    '''
    
    # getting the correct rows x cols shape
    features = np.zeros((len(reviews_ints), seq_length), dtype=int)

    # for each review, I grab that review and 
    for i, row in enumerate(reviews_ints):
        features[i, -len(row):] = np.array(row)[:seq_length]
    
    return features

In [17]:
seq_length = 15

features = pad_features(coded_revs, seq_length=seq_length)

In [18]:
for i in range(len(coded_revs)):
    print(features[i],classes[i])

[   0    0    0    0    0    0    0    0    0    0   73 3299   18 4547
 4548] [0 1 0]
[   0    0    0  273    4 1334  140  278   13    3  140  193   82    5
   80] [1 0 0]
[   0    0    0    0    0    1  358  553 4549    6  103  132   53  359
  680] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0 489] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0 326  41 218  52   2] [1 0 0]
[   0    0    0    0    0    0    0  964  220 1335   46  227   51  641
  144] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0 1184  100 3300 3301
  662] [1 0 0]
[   0    0    0    0    0    0    0    0   29  228   11 1336   11  142
    6] [1 0 0]
[   0    0    0    0    0    0    0   24   38 2680  847  642 1798    6
 4550] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 965 312] [0 0 1]
[   0    0    0    0    0    0    0    0    0  285   49 4551  326   41
 1008] [1 0 0]
[  0   0   0   0   0   0   0   0 248   1 110   5  37  52 602] [0 1 0]
[   0    0    0    0    0    0  

 1675] [0 0 1]
[  0   0   0   0   0   0   0   0   0 470 580  77 100 101 106] [1 0 0]
[   0    0    0    0    0    0   25  130  470  166  652   31  609 1829
   60] [1 0 0]
[   0    0    0    0  685  203  265  102    5   37    1  760 3356 1830
   69] [0 1 0]
[   0    0    0    0    0    0    0    0    0    1   58  426  223  300
 1831] [0 1 0]
[3357 2723   16  120  717  160  560  114  133  278   17 4664 4665    1
  129] [1 0 0]
[   0    0    0  884  572   36 2040 2331   12 2724  572 4666  884 2041
  203] [1 0 0]
[  0   0   0   0 230  45 419  15  81  32  45  89  18  17  53] [1 0 0]
[   0    0    0    0    0    0    0    0    0  652   25 1139 1139 1139
 1139] [0 0 1]
[   0    0    0    0    0    1 1533 1078 2332 2315   75    7  200 2685
 1350] [0 1 0]
[  0   0   0   0   0   0   0   0   0 251  28   7 301  19 826] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0  216 1351
  983] [0 1 0]
[   0    0   29   22   55   14  330 1676   41    3  293   13   33    1
   79] [1 0 0]
[

[   0    0    0    0    0    0  558   35  179  574    8  384    7  164
 2062] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0 1033  309   16
 4755] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0  31 520 158 148] [0 0 1]
[   0    0    0    0    0  833   31   11   34  175  122  142  238 1552
 4756] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   2 944 373] [0 0 1]
[   0    0    0    0    0  109   89   21 4757 1034 2747   21  352   21
  288] [1 0 0]
[   0    0    0    0    0   16  130   46 3398 2063 2748  625  186  763
   86] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0  16 298  69] [0 1 0]
[   0    0    0    0    0    0  744 1845   14   99  157 4758  766   79
   95] [1 0 0]
[   0    0    0    0    0    0    0    0   46   83  648  105  632   74
 4759] [0 0 1]
[   0    0    0  212    1 3399 1836  524  241 1035 2749  206  241    1
 3400] [1 0 0]
[  0   0   0   0   0   0   0   0   0 106 705 905  24 870 132] [0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] 

[  0   0   0   0   0  16  27   1 717  23  27  92   8   1  93] [1 0 0]
[   0    0    0    0    0 4861 3456  708    1  222  349  203 1699   75
  609] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    7   65 3457
  120] [1 0 0]
[   0    0    0    0    0   73  170  645  580  183  859   77   60  719
 2094] [1 0 0]
[   0    0    0    0    0    0    3    6   55   14 1103  143 1459 1362
   25] [1 0 0]
[  0   0   0   0   0   0   0   0   3 523 567 108   1 276 795] [1 0 0]
[   0    0    0    0    0  180   13    3  822 1380 1460   88  318   35
   18] [1 0 0]
[   0    0    0    0    0    0    0  148  437  852  203   86   35 1706
  411] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0 422 455 455 123 124] [0 1 0]
[   0    0    0    0    0  805 1045  208 1228   26   10   20 1045  121
 1228] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   1 300 688] [0 1 0]
[   0    0    0    0    0    0    0    0   18   44    1   15  803   28
 1432] [1 0 0]
[   0    0    0    0  870  975  

[  0   0   0   0   0   0   0   0   0   0   2 453 309 193  42] [1 0 0]
[   0    0  195  289  647  185  165    2  944   17  198   84 1047  244
  465] [0 0 1]
[   0    0    0    0    0    0    0    0    0    2    8   34   25 2837
 2814] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0 4922  114  528
  256] [0 1 0]
[   0    0    0    0    0    0    0   22  427 1874 1565  256 1358 4923
   24] [0 1 0]
[   0    0    0    0    0  335  347   84    9    4   57  267   18 3493
   36] [1 0 0]
[   0    0    0    0  466 1160 3494   12   60  153   12  580    1    5
   37] [1 0 0]
[   0    0    0    0    5 1200    1  557   51  606 1680  101  137   97
   28] [1 0 0]
[   0    0    0    0    0    0    0    0   24  459 1348 2405 2122  494
  104] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0   59   36  169 2098
   36] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0  16 461  32   1] [1 0 0]
[   0    0    0    0    0    0    0   73   71 

[  0   0   0   0   0   0   0   0   0   0   0 226  58  87 441] [0 1 0]
[   0    0    0    0    0    0 2427   47   30  297 2871 1539 5018    1
 5019] [0 1 0]
[   0    0    0    0    0    0    0    0    0  301 5020    8 1364 1242
  209] [1 0 0]
[   0    0    0    0    0    0   34  424  372  369 2872   27    1 3549
 5021] [0 0 1]
[   0    0    0    0    0    0 1735 1243  541   36  434  176  187    1
  108] [1 0 0]
[   0    0    0    6    1    3   38  366   98  204  117  118   61 1855
 5022] [1 0 0]
[   0    0   24 2381   14 5023  470   40  546  122  583 3407    7  272
 5024] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 8] [1 0 0]
[   0    0    0    0    0    0    0 2344 1700 5025 1142   10   54   10
  488] [1 0 0]
[  0   0   0   0   0  18 348   9   4  19 171 522  84  49  86] [1 0 0]
[   0    0    0    0   25   30   28    9    4 5026   29   51   93  147
 5027] [1 0 0]
[   0    0    0    0    0    0    0    0  605 1089   30    7 3441  181
 1068] [0 0 1]
[   0    0    0    0    0    0    0    0    0 

  551] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 101 248] [1 0 0]
[  0   0   0   0   1   9  55  14  13  78 387  86 110   3   6] [1 0 0]
[   0    0    0    0    0 1239   34 1172    1  147  155 1094   15   14
  276] [1 0 0]
[   0    0    0    0    0    0    0    0   64   71 5114 2166  473 1249
 2897] [0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[   0  334  162    5   80  103    6 1589    1   42   33  113  217   52
  312] [1 0 0]
[  0   0   0   0   0   6   7 162  75  13  45  23 216 505 705] [1 0 0]
[  0   0   0   0   0   0   0   0 189   3   3  13   7  23 363] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0 34 54 66] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
 3592] [0 1 0]
[   0    0    0    0    0 5115  329 1090 1090 1090   64   11  371  426
  836] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0   12    7  251
 1596] [0 0 1]
[   0    0    0    0    0  770   26   10  323  222   11   82   93   70
 3593] [0 1 0]
[0 0 0 0

    8] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 232  22  43] [0 0 1]
[   0    0    0    0    0   47  346  276 2450   35  427  145  122  346
   44] [1 0 0]
[  0   0   0   0   0   0   0   0  50  60 446  33 113   2 237] [1 0 0]
[   0    0    0   36   81 5205 2178  360    4  284  315  198  935  723
   46] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0 2912  683  216   15
    3] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0 5206  425
  370] [1 0 0]
[ 0  0  0  0  0  0  0  0 13  7 45 41 13  7 94] [1 0 0]
[   0    0    0    0    0    0    0    0    0 5207  153  496   49  658
  146] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0 5208  146   14  721
 1445] [0 0 1]
[  0   0   0   0   0   0   0 199  18 158  19 270 143  27   1] [1 0 0]
[  0   0   0   0   0   0   0  18 588  59  55  28   3 293  12] [1 0 0]
[  0   0   0   0   0   0   0  88 293   3  18 803  38   1 239] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0   25  281   5

[   0    0    0   26  186 1396 1618  242   16 2927  242  490  366  548
  309] [0 1 0]
[   0    0    0    0   15   45  162   12 5290  400 1319  289   76  485
   18] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 165  50] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0 2104    7   12
   97] [0 1 0]
[   0    0    0    0    0    0    0    0    0  125  317 1619    2   47
  874] [0 0 1]
[   0    0    0    0    0    1   95  315  315 1767  945    1 3651    5
   37] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0  29 132  74  14] [1 0 0]
[   0    0    0    0    0    0    0    0  325   20  119  325   20 3652
  132] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    0   40 2089
   60] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[  0   0   0   0   0   0   0  19  18 348 749   9   4  27   1] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 125  91] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0 121 127 176   1  66] [1 0 0]
[   0   

   10] [0 1 0]
[   0    0    0    0    0  370   46   97   35   26   79 1001  321  125
  960] [0 1 0]
[   0    0    0    0    0    0    0    2   50  446  454 3705 5425  130
 5426] [0 0 1]
[   0    0    0    0    0    0    0   60  368   50 1143   74   25   17
  679] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0  845   12 5427
  884] [0 0 1]
[   0    0    0    0    0    0   38   20 5428  982  305   17  283  168
    2] [1 0 0]
[   0   25 5429   94    7 5430  316  110  209  125  378  274 3706  469
  951] [0 0 1]
[  0   0   0   0   0   1  13  10  26   3 147  59  38  98   8] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0 214  15   3 419] [1 0 0]
[   0    0    0    0    0    0    0    0    0  134 1674 3707  707  805
 1657] [0 1 0]
[  0   0   0   0   0   0   0   0  91 919 237 551 299   9   4] [1 0 0]
[   0    0    0    0    0    0    0   48  425    6   48   17   15 1339
 2967] [1 0 0]
[  0   0   0   0   0   0   0  73  10  82 984 118   2  34 424] [0 0 1]
[   0    0    0  

  326] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[   0    0    0    0    0  199  601 3742    7  271  804 1144  212    1
   85] [1 0 0]
[   0    0    0    1   95 5497   41 1861 3687 2521 2212  105 5498   11
   48] [1 0 0]
[   0    0    0    0    0    0    0 2070   45   13    7  111   12    8
  111] [1 0 0]
[  0   0   0   0   0   0   0  24  41  28 103   8  40 234 149] [1 0 0]
[   0    0    0    0    0    0   60 5499  550  562   24   41 5500  146
    8] [1 0 0]
[   0    0    0    0   83  285   81   22   17  295    1 5501  175  271
    1] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0 123 124 329 329 329] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
 5502] [0 1 0]
[   0    0    0    0    0    0    1  110 1777   43  914   52    5   80
    8] [0 1 0]
[   0    0    6 5503  898   24  405   38   98  209 1175   12  405   32
    8] [1 0 0]
[   0    0    0    0    0    0    0   60 3743 5504 2434 2990  453   61
 1398] [0 1 0]
[   0    0    0    0    0    0 

 5589] [0 0 1]
[   0    0    0    0    0    0    0 3780 2929  187 1527    5   37   18
   15] [1 0 0]
[   0    0  629   10  179   59  162   10  526  126    1  510    1  135
 3541] [1 0 0]
[   0 5590  170  374 3781   47    8  529   10    3   33  113 5591 5592
 1310] [1 0 0]
[   0    0    0    0    0    0   25 3782  484  551 1221  148  121   41
 5593] [1 0 0]
[   0   18  169  432  294 1350   28   60   81  247   33  113   48  237
  148] [1 0 0]
[   0    0    0    0  203 3783  594   27  392  640   76   45   13    7
    2] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0 5594  123
  124] [0 1 0]
[   0    0    0    0    0    0    0    0    0  394   35  205 5595   26
  191] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0  87  23 541  43] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0 215 728 597 597] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0    0    0 1485
    1] [0 1 0]
[  0   0   0   0   0   0   0   0 605 438  99  11  31  34  87] [1 0 0]
[

    2] [0 0 1]
[   0    0    0    0    0    0    0  135 1715   85   42  476  263  462
  281] [1 0 0]
[   0    0    0    2  197    4  231 1078   19   17   70  298 1434    1
 1309] [1 0 0]
[  0   0   0   5   1   1  43 159 116 183  13  45  15 139 768] [1 0 0]
[   0    0    0 3841 5738    6  140 1439  722  304  139    5   37    1
 3842] [1 0 0]
[  0   0 891  50  10 776 202 386 526  23   1  27  52 282 139] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0   58   85 2559
 1932] [1 0 0]
[  53   15    7  107  992 3040  586  114  921 1018 3843  112  132  768
  186] [1 0 0]
[   0    0    0    0    0    0    0    0 3041   12  118   22   99   23
    1] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    9    4
 1638] [1 0 0]
[   0    0    0    0  149   27   39    5    1  770   39   17  206 1589
   92] [0 1 0]
[  0   0   0   0   0   0   0   0   0 161 219 865 197   9   4] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0 178 224 123 124] [0 0 1]
[   0    0    0  

 5792] [0 0 1]
[   0    0    0    0    0    0    0  139 5793   32 1351 2769  771 1761
 1208] [1 0 0]
[   0    0    0    0    0    0  436  667  515  416  185  140    1  326
 1096] [1 0 0]
[   0    0    0    0   71   55  217 3340 5794   95 5795  502 3302 3051
   14] [1 0 0]
[   0    0    0    0    0    0   21  892 2128  420 1071   86   30 1071
  420] [1 0 0]
[   0    0    0    0    0    0    0    0 3401 3402 5796 1316  283 3403
 3867] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0  253   86 1112
 2191] [0 1 0]
[   0    0    0 1630    1    5   80 2570   95  580 1686  159  468  248
  155] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0 59 88 35] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   1 135 218  14   8] [1 0 0]
[   0 5797  133   36  140   33    1   99  133   62  255   11   61  136
 1448] [1 0 0]
[   0    0    0  693 2363 2759  120  256 1415 5798 5799 1262 1464  185
  424] [0 0 1]
[   0    0    0    0    0    0    0    0   63   21 5800 3052  371 1965
  191] [1 0 0]


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0    0  105  370
 5905] [0 0 1]
[  0   0   0   0   0   0   0   0  15   9 104 481 263  28 218] [1 0 0]
[   0    0    0    0    0  243    1   27  661  610   41  111   40   49
 5906] [1 0 0]
[  0   0   0   0   0   0 278   1   6 174 156  25  21  89 288] [1 0 0]
[  0   0   0   0  23  13  53 143  28  27 175 836 243  27  92] [1 0 0]
[   0    0    0    0    0    0    0 3914  384    7 3025    9    4    2
 2240] [1 0 0]
[  0   0   0   0   0   0   0   0 229 226 526 233  16 225  20] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   2 162 290] [0 0 1]
[   0    0    0    0    0 1788 1973   64  977 1684    1   72  881 1551
  331] [0 1 0]
[   0    0    0    0    0    0    0    0    0  164 3069    1    5   37
  590] [0 1 0]
[   0    0    0    0    0    0    0 1344   13   45   44   39 5907  146
  203] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 91] [0 1 0]
[  0   0   0   0   0   0   0   0   0   

[  0   0   0   0   0   0   0   0   0   0   0   0   0   2 111] [0 1 0]
[   0    0    0    0    0 1209  272  324 2051   10   61   47  101  194
  297] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0  62  60 174 156] [0 1 0]
[   0    0    0    0   47  158    1  775  132 1442 1204  457   87  371
  426] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0 2750 2751
  583] [0 1 0]
[   0    0    0    0    0    0    0    0    0  272  280  255 5994  689
 1107] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0 191] [1 0 0]
[   0    0    0    0    0    0    0  397   48 1013 1642   74 1358   11
   68] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    2   11  320 5995
 3093] [0 0 1]
[   0    0    0    0   90    9    4  160 1827  513  833  279  393  160
 5996] [1 0 0]
[   0    0    0    0    0    0    0 5997   46  227    1  127    2   46
    1] [0 0 1]
[  0   0   0   0   0   0   0   0   0   1 209 108 244 355  41] [0 1 0]
[   0    0    0    0    0    0  

[  0   0   0   0   0   0   0   0   0   0   0  34  19 275   2] [0 0 1]
[   0    0    0    0    0    0  257 6058 1866  318  612 1569 1099 3973
    7] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   1 209 236] [0 1 0]
[  0   0   0  48  54  10 102  10 175 554  73  65 360 732  40] [1 0 0]
[   0  713  384    7   50   48  400  562   17   62   48  598 1438 1010
 1747] [1 0 0]
[   0    0    0    0    0    0    0    2  180   10  785  576  132  135
 3107] [1 0 0]
[   0    0    0    0    0    0    0    0  507    5    1  200  306   38
 1050] [1 0 0]
[  0   0   0   0   0   0   0   0 857 236  32 754   7  47  26] [0 1 0]
[  0   0   0   0   0   0 616 334 193  42  20 493 640 753 450] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1] [0 1 0]
[   0    0    0    0    0    0    0    0    0  319 6059 3974 6060   43
  328] [0 1 0]
[   0    0    0    0    0    0    0 1029    1  458 1010  655 1010 6061
  195] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 651  34  25] [0 0 1]
[  0   0   0   0   2  12

 1126] [0 1 0]
[   0    0    0    0    0    0    0  573 6174  150  346   14   82  367
  439] [1 0 0]
[   0    0    0    0    0    0 6175   16  796 6176 2845 1281 2100 1194
   85] [0 1 0]
[   0    0    0    0    0   38 4004    7  842 6177 1668   38   98    7
    1] [1 0 0]
[   0    0    0    0 1975 4005 4006 1216  525    8   70   78   54   17
  208] [1 0 0]
[   0    0    0    0    0    0    0    0  118   36 2202  177 6178  512
   29] [1 0 0]
[   0    0    0    0    0  120   60 1066  185  422  457  133  531  313
  248] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 416 797] [1 0 0]
[   0    0    0    0    0    0    0    0    0    2  105  554 1340 4007
  367] [1 0 0]
[   0    0    0    0   32    9    4   17  120 6179 6180  229  658   17
   23] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0 182 110 182 176] [0 1 0]
[   0    0    0    0    0    0    0    0  481 3704  635   22  832 1407
  451] [1 0 0]
[   0    0    0    0    0    0    0    0  253 6181   45   13    3 4008


[  0   0   0   0   0   0   0   0   0   0   0   8  76 133  28] [1 0 0]
[  0   0   0   0   0   0   0   0  11 451 260  74 197   9   4] [1 0 0]
[   0    0    0  353  434 6283  887  261    5    1    1   72    7   85
    1] [1 0 0]
[   0    0    0    0    0    0    0    0   25  180 6284  702  297   63
 6285] [0 1 0]
[   0    0    0    0  293    3   15   90  235   25 6286 2609  532   61
  279] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0   92  466 1328
   28] [1 0 0]
[   0    0    0  101   14    3   33    1 2409  200 1622 6287  288   94
    7] [1 0 0]
[   0    0    0    0    0   73  489  272   31   82 2353    7  264 1225
   13] [1 0 0]
[   0    0    0    0    0    0    0  259  924   31 3060  397  702   36
 1643] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[  0   0   0   0   0   0 350 583  29   4  74 105  58 205 536] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 722  27  14] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0 3337  454 1815 6288
 6289] 

  740] [1 0 0]
[  0   0   0   0 318 943 915  14 344  20 131   3  33   1 137] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0   89 1392   90   12
   56] [1 0 0]
[   0    0    0    0    0    0  213   30 6351 6352  534   31 6353  169
 6354] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0 162  12   3 485   2] [1 0 0]
[   0    0    0    0    0    0  431   22  390  619 1550    9    4   34
 1381] [1 0 0]
[  0   0   0   0   0   0   0  34 141 175  27   1 187  52 602] [0 1 0]
[   0    0    0 6355  490 1280    1 1436  738   41  796  178   98  134
  571] [0 0 1]
[   0    0    0    0    0  507 6356  136  389  152  295    1 6357   32
  125] [0 1 0]
[   0    0    0    0    0    0    0 6358   99   62   27   76   92  384
    7] [1 0 0]
[  0   0   0  15  81   9   4  88  45  28  35  53 316 780 318] [1 0 0]
[   0    0    0    0    0  340    7  350   14  325    6  304   57 6359
 6360] [1 0 0]
[   0    0    0    0    0    0    0    0    0  169    1  116   36  130
 1488] [1 0 0]
[  0   0   0   0 

  532] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0 1881 1124  841 1178
 6451] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 90] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    0 4089   67
  657] [0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1] [0 1 0]
[   0    0    0    0    0   43  120  110  553  161  991 1051  537 2076
   11] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 604 187 499] [1 0 0]
[   0    0    0    0   16  272  687 3914   25   36 6452 2260 2261  357
  184] [0 0 1]
[ 35  99  15  98 121  33   1  53 200   7  53  33   1 119  20] [1 0 0]
[   0    0    0    0    0    0    0    0    0  363  812  237 1395   60
  191] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  440  119  167 6453
   19] [0 1 0]
[   0    0    0    0    0  125 2241 4090   67  298  581  395  520  411
   50] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0  409  630  540   63
 1132] [0 1 0]
[  13    1  675 3155  759 1857   48  540   33  113    1   17  

  172] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 46] [0 0 1]
[   0    0    0    0    0    0 6512   83   26   59   75  283   56    7
   13] [1 0 0]
[   0    0  846   12   14   15   21 3512  214  414  174  156   61 3845
  195] [1 0 0]
[   0    0    0    0    0    0    0    0    0  558  158  151 1174  452
   88] [1 0 0]
[   0    0    0    0    0    0    0    0    0  245 1485  625   54  152
  211] [0 1 0]
[   0    0    0    0    0  312   51    6  879  363 6513   79   27 6514
 2350] [1 0 0]
[   0    0    0   47  120 1366 3168 4113  141  425   26   10 3169 3170
  275] [1 0 0]
[   0    0    0    0    0    0    0    0  142  538  256    1  321   43
 1053] [0 1 0]
[   0    0  759 1175  110  786 6515  176  272 1755 2124  110  108   27
   98] [0 1 0]
[  0   0   0   0   0   1 162 121 315  44  66 351 346   1 439] [1 0 0]
[   0    0    0    0    0    0    0    0 3171  804   44    1   47  893
 1046] [1 0 0]
[   0    0    0    0    0    0  106 1520 2553 6516   29    9    4  160
 6517] [1 0 0]


 2152] [1 0 0]
[   0    0    0    0    0    0 6583  516   14  204   78  249 4135   45
    6] [1 0 0]
[   0    0    0    0    0    0    0    0   22 3182  926  710  793 2977
 3183] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0   18 1994 1330  577
   36] [0 1 0]
[   0    0    0  236 1113 1532  177    5   80   51 3139 1287 1843 2019
 1314] [1 0 0]
[  0   0   0   0   0   0   0 264 390 272  23 122  34 277 390] [1 0 0]
[   0    0    0    0    0    0    0    0    0    5    1    1  611   32
 6584] [1 0 0]
[   0    0    0    0    0    0    0 3467 2812   71   32 1995   99   23
  149] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[   0    0    0    0    0    0    0    5  495  291  159   31 1481  478
   57] [1 0 0]
[   0    0    0    0    0    0 1996 1427 2447    1  271  343   19  758
   36] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 753 450 847] [0 0 1]
[   0    0    0    0    0    0    0   41  244 2080 1298   25   36  607
 2081] [0 0 1]
[   0    0    0    0    0    0 

[   0    0    0    0    0    0    0    0    0    0   48  191  264 4160
  943] [1 0 0]
[   0    0    0    0 3192  141  415  760  145 1988 2240   10   11  571
   77] [1 0 0]
[   1  187  209  112   13  209 2562 1281 1207   38  119  209 6666   90
  159] [1 0 0]
[  0   0   0   0   0   0   0   0 165   1 108 165  72 135 126] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0  409  394 1133 1263
 1051] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0   51
 1169] [1 0 0]
[  0   0   0   0   0   0   0  26   1 296 248   6   5  37 497] [0 1 0]
[   0    0    0    0    0   38  543  193 2443  176 6667   93 2070   19
 2070] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0  15  14 369] [0 1 0]
[   0    0    0    0    0   27  212    1 1715   95  202  351 6668  351
  972] [0 1 0]
[   0    0    0    0    0    0    0    0    0 2074  266  629  730    4
 6669] [0 0 1]
[   0    0    0    0    0    0    0    0   64  232  579    1  131 3416
 3931] [0 0 1]
[  0   0   0   0

   40] [1 0 0]
[   0    0    0    0    9    4  197  501 6796    3    1    3   33  113
 6797] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0  28  46 667 677] [1 0 0]
[  0   0  33   1  14  38   1  72 380  87  20 344   7   9   4] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    0  253 1244
  940] [0 0 1]
[   0    0    0    0    0    0  938 1424    4  222  271 6798 6799  511
   57] [1 0 0]
[   0    0    0    0    0    5   37    1    1   19   16    8 1293 3208
 1534] [1 0 0]
[   0    0    0    0    0    0    0    0    0   94  171   39 4190   44
    1] [0 1 0]
[   0    0    0    0    0   63  406 1466   85 1383   79  585 6800  927
 6801] [0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[  0   0   0   0   0   0   0   0  42  66  78 179 945 377 201] [1 0 0]
[   0    0    0    0 1411   59   31 6802 6803  401   90 4191  651  360
    4] [0 0 1]
[  0   0   0   0   0   0   0   0   1 121  33   1  42  79  98] [1 0 0]
[   0    0    0    0   

[  0   0   0   0   0   0   0   0   1  58 164   5  37 200 355] [0 1 0]
[   0    0    0    0    0 6875 6876  447  886 3219 6877   59   30  196
  370] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0 123 124 370 431] [0 0 1]
[  0   0   0   0   0   0 683  13 683  13  14  41 346  30 276] [1 0 0]
[   0    0    0   14  448 1556   13   16 3220  555 2275 2916    8  121
 2275] [1 0 0]
[   0    0    0    0    0    0    0  235 6878 1034  352   61  204  388
  346] [1 0 0]
[  0   0   0   0   0   0   0   0   0  73  40 362   3 263  88] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0   64   63  152
 1476] [0 0 1]
[   0    0    0    0    0   15    9    4   65  588 4214   17   15   53
  107] [1 0 0]
[   0    0    0    0   36   11 1243  352  490 1688  183  230   38 1156
  468] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 488  50] [0 1 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  1 43] [0 1 0]
[   0    0    0    0    0    0   11   52 2059    5    1  370 1769  357
  184] [

[  0   0   0   7   1   6  38   1   7  54  78 716 512   1 195] [1 0 0]
[   0    0    0    0    0 4229   65  128  237   42   69   83  128 1491
    9] [1 0 0]
[  0   0   0   0   1 809 249   9   4 150 289  21  89 288  57] [1 0 0]
[  0   0   0   0   0   0   0   1 129 207 761  87  29 990 990] [1 0 0]
[   0    0    0    0    0    0    0  291  173   24 2499   60  509  750
 1989] [0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[   0    0    0    0 6963  144  603    9    4 1130  105  149   85    9
  139] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  125  340   36   89
 6964] [1 0 0]
[   0    0    0  206   39  323 6965  626   12   60 1583   68  250   37
   39] [1 0 0]
[  0   0   0   0   0   0   0   0   0 125  91  67 130 374 193] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0   10 4230  512
   10] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0  196  222 1862
   66] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
 6966] 

  124] [0 1 0]
[   0  252   20   35  138  501   88   13  375  129  207   38    1 4215
  339] [1 0 0]
[   0    0    0    0    0    0    0    0    1  205   25    1  223    4
 1326] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0    0  765    1
 1423] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   2 247  18 374 110] [0 0 1]
[  0   0  86   3  33   1 300 896  66 219 501  94  88  78 732] [1 0 0]
[   0    0    0    0    0    0 7091 2049  197 1610   30  355  314  972
  111] [0 1 0]
[   0    0    0    0    0    0    0    0    0  120 1275  604 1182  685
  109] [1 0 0]
[   0    0    0    0    0  448 2278   26  333 1410 3414   26   10  243
 1159] [1 0 0]
[   0    0    0    0    0    0   14   19   71  732  217 2645  218  220
  176] [1 0 0]
[   0    0    0    0    0    0   21  715  109  579  142  242 7092 7093
 7094] [1 0 0]
[   0  846 7095  167   10   26 1271  414 7096 1171  138 7097  275    9
 1969] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[ 0  0  0  0  0  0  0  0  0  0 

    6] [1 0 0]
[   0    0    0    0    0    2  687   75  115  189 2624   10  846  566
  115] [1 0 0]
[   0    0    0 7184  317    6 2064 1395   20   35   29 1026  686   29
  209] [1 0 0]
[   0    0    0    0    0    0   57  342 2273  774   33    1   20   35
    3] [1 0 0]
[  0   0   0   0   0   0   0   2  68 180 252  31  10  47 211] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0  466   69
 7185] [0 1 0]
[   0    0    0    0    0  323  712  150   13    3   15  101  323 1092
  157] [1 0 0]
[   0    0    0    0    0    0    0    0   58  395    1   32    5   37
 4274] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0  24  69 514] [0 0 1]
[   0    0    0    0    0    0    0 4275   11    4   93  741  230  211
  741] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0  297
 2869] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0 1327 3234
  411] [1 0 0]
[   0    0    0    0    0   23  117  220  178  896 1161 7186  135  178


[   0    0    0    0    0    0    0  279  604   22 3900   11  567   11
 2555] [1 0 0]
[   0    0    0    0    0    0    0    0   30   42    1  637  225   98
 1255] [0 1 0]
[  0   0   0   0   0   0   0   0 199 196   1 193 300  40  57] [1 0 0]
[   0    0    0    0  765   19    6 1369    6 1312   13  210   20  480
  480] [1 0 0]
[   0    0    0    0    0    0    0 4174   23  206  546  714    1    6
    3] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0 115  43   1 765] [1 0 0]
[  0   0   0   0   0 249 486  66   4 236 448  26 518  10 618] [1 0 0]
[   0    0    0    0    0    0  449  403  297  134  255 1216 2097    1
  131] [1 0 0]
[  0   0   0   0   0   0   0   0  18 135  60   9   4 306 104] [1 0 0]
[   0    0    0    0    0    0   24   79 1005  209  341  167    1   42
  111] [0 1 0]
[   0    0    0    0    0    0    0   35    8  189 1295  695  288   34
 2622] [1 0 0]
[   0   83  150 1519  985   81   29   79  126    1  149   12 7264  155
    2] [0 0 1]
[  0   0   0   0   0   0   0   0

 1552] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0 2848  281   34  436
  139] [1 0 0]
[   0    0    0    0    0    0    0    2 1262 7368  563  659 3502  280
  331] [0 0 1]
[   0    0    0    0    0    0    0  539   87   39    5   80 1538   77
   67] [1 0 0]
[   0    0    0    0    0    0    0    0  168 1768   24   78 2239   81
  817] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0  203 3239 1844
  879] [0 1 0]
[  0   0   0   0   0   0   0  13  10   1 190 152  79 219   4] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0 15  3] [1 0 0]
[   0    0    0    0  488 7369 4149   36 2499 7370  999  449 1457   61
 1097] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0 1724   25  517
 2994] [0 1 0]
[   0    0    0    0    0    0    0    0 1397 7371 7372   10 1093    1
  128] [1 0 0]
[  0   0   0   0   0   0  48  72 240  13  23  45 147 135  20] [1 0 0]
[   0    0    0    0    0    7  136  152   66  181   38 1856  615 1167
  496] [1 0 0]
[   0    0    0 

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0 312] [0 1 0]
[   0    0    0    0    0    0    2  247 2320   67   31  144  360  160
   24] [1 0 0]
[  0   0   0   0   1 351   5  80 112 229  65 295  23   1  32] [1 0 0]
[   0    0    0   12  225   32    9    4   17 1648    9  639   89  306
    8] [1 0 0]
[   0    0    0    0    0    0    0    0 1128  594  869  694  172  311
  978] [0 0 1]
[   0    0    0    0    0    0    0 2682   87   18   36  641   23  612
 3740] [1 0 0]
[  0   0   0   0   0   0   0   0  23   1 110 167   5  37  52] [0 1 0]
[   0    0    0    0    0    0    1  241  110    5   37  430  379 4333
   32] [1 0 0]
[   0    0    0    0    0    0    0    3   50   14 3001    1   95  619
  238] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0 270 149  47  97  28] [1 0 0]
[   0    0    0    0    0    0  736   66 7492  416  276 7493 1105  382
   60] [1 0 0]
[   0   66 2517 7494   38 1102   82   78  179  269   66   35 7495   83
    8] [1 0 0]
[  0   0   0   0   0   0   0   0

  138] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0   64  997  805 7569
 2157] [0 1 0]
[   0    0    0    0    0  840  550 1375  562  406   88 1407  995 3976
   12] [1 0 0]
[   0    0    0    0    0  523  567    1 7570  172 7571 1115  694  715
  494] [1 0 0]
[   0    0    0    0    0    0    0    0  251 7572 7573   65  154    9
    4] [1 0 0]
[  0   0   0   0   0   0   0   0  25 104   9 106  12 296 413] [1 0 0]
[   0    0    0    0    0  225   20  154    1    9    4   62   14 1316
  231] [1 0 0]
[   0    0    0    0    0    0    0    0    1    5  192  403  838 2319
 2319] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 178   9   4] [1 0 0]
[   0    0    0   15  168   41    1 1489  567 4248    8  332  383   97
  611] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0   25  710  272
 7574] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0 1211  290 1787   47
   18] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    0  143 2793


[  0   0   0   0 213  47  63 327 216 134 320  64  11  34  90] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0  45  15 279 120 383] [1 0 0]
[   0    0    0    0    0    0    0    0    0  609 1279  481   34  171
 1992] [0 1 0]
[   0    0    0    0    0  153  191  264    7 1110  524    9    4 3014
 3076] [1 0 0]
[   0    0    0    0  692 2286 2925   16  382  121  110  321 1255   66
  314] [0 1 0]
[  0   0   0   0   0   0   0   0   0 309   9   4 120 803 429] [1 0 0]
[   0    0    0    0    0    0    0   62   30   50  292  529  162 1940
  208] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0 162] [0 0 1]
[  0   0   0  29 632  74 347   1 217 200 167 103  33 113 313] [1 0 0]
[   0    0    0    0    0    0    0    0    0   38 1026 7601   45  594
  437] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0 3157   14
  238] [1 0 0]
[   0    0    0    0  116    1  129  207   74 3877 7602 7603 1059  293
 2497] [1 0 0]
[  0   0   0   0   0   0   0   1  20  35  14 328

    1] [1 0 0]
[   0    0    0    0  158   76 1342  183 2293  203  859  114  810  136
  183] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0 18 32] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 101  29  74] [1 0 0]
[  0   0   0   0   0 273 853 401 233   1 218  16 367 217   6] [1 0 0]
[   0    0    0    0    1    5   80    6  248  507 1316   39  118   17
    1] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0 1405
  287] [0 1 0]
[   0    0    0    0    0  619 3162   43  275    9 7706 1595  360  691
 1260] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0  25 517 110 650  86] [0 0 1]
[  0   0   0   0   0   0   0   0   0  52 203   1 210 250  37] [1 0 0]
[   0    0    0    0  931  177  152  553 3113  442   21  324 1034  734
   19] [1 0 0]
[   0    0    0    0    0    0    0    0    0 1922   44  334  116  323
   27] [1 0 0]
[  0   0   0 243 318  10   1 225  33   1 359  42   3  33   1] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    

  733] [1 0 0]
[   0    0    0    0    0    0    0 7787  222  191   68    3  222  186
   47] [1 0 0]
[   0    0    0    0    0    0  253  194   25   58  395 3240  533  673
    2] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0  67 711 171] [0 1 0]
[   0    0    0    0    0    0   12 1536    1   41  747   42  130  145
  276] [1 0 0]
[   0    0    0    0    0    0 2203  481  469 4394 4395 2061 3013  738
 1248] [0 1 0]
[  0   0   0   0   0   0   0   0   0  25 201 643  58  11 492] [0 1 0]
[   0    0    0  115   67  794  664   27    1   32  620 1605  487  924
  314] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0   17   14
 7788] [0 1 0]
[   0    0    0    0    0    0    0 2423 2867   12  668  475   35  449
 2110] [0 1 0]
[   0    0    0    0    0    0   45    1 1324   13   45  277   20 1226
 7789] [1 0 0]
[   0    0    0    0    0   46  313   33    1  181    4  260 2977  104
 1364] [1 0 0]
[   0    0    0    0    0   12  153 1555   18  306   12  107   29    9


[   0    0    0    0    0    0    0    0    0    2   34   25 1763  357
  184] [0 0 1]
[   0    0    0    0    0    0    0   71  865   63 2315  190  110  806
   22] [0 1 0]
[   0    0    0    0    0    0    0    0    0   83 7880   30   24  193
   42] [1 0 0]
[   0    0    0    0    0    0  106   48   56   19 2119 4414 7881 7882
 3538] [1 0 0]
[   0    0    0    0    0    0   29   71   19  298   60 2277   93  179
   93] [1 0 0]
[   0    0    0    0    0    0    0    0  367   85  149  104 7883   54
  177] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 765 431] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   6   3  18 100] [1 0 0]
[  0   0   0   0   0   0   2  86 136  32  12  63   1   5  37] [0 0 1]
[1585    6 4415  867 1766 1766  867 1222 1222  867 1766 1766  867 4415
  134] [1 0 0]
[   0    0    0    0    0    2  369   84   18  265 7884  633   46    8
  265] [0 0 1]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0 31 91] [0 0 1]
[   0    0    0    0    0  278 1835 2953  710  

  233] [1 0 0]
[  0   0   0   0   0   0   0   0 106 167 127 168   6 249 408] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 458 156] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0 4444   45   15
 2651] [1 0 0]
[  0   0   0   0   0   0   0   0   0  83   1 193 330 416  26] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0  253  431 2997  123
  124] [0 1 0]
[  0   0   0   0   0   0   0   0   0  30 573  51 573 275   9] [1 0 0]
[   0    0    0    0    0  164    8  226  540    1    7 2395  218   32
    1] [1 0 0]
[   0    0    0    0    0    0    0    2   84   72  935  354   29   41
 1515] [1 0 0]
[   0    0    0    0    0    0  142   85  268  202  150 1142  470  454
  238] [1 0 0]
[   0    0    0    0    0    0    0   67 2197   44  118  204  117 1860
 8022] [1 0 0]
[   0    0    0    0    0    0   15    1    5   37   17 2671  138  198
 2084] [1 0 0]
[   0    0    0    0 2257 3211  472 2485 4416 4417 3131 4418 4419  215
  502] [0 1 0]
[   0    0    0  

   85] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0 3883   84 3209
   57] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0 2468
 1317] [0 1 0]
[   0    0    0    0    0  875   46  149   60 1912  228  281  237 1323
 1501] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0 1656
  173] [0 1 0]
[   0    0    0    0 3073   63  592 3738  216  703  114   27  392   39
  323] [1 0 0]
[  0   0   0   0   0   0   0  29  22 231   3   3   6   1 117] [1 0 0]
[   0    0    0    0    0   13  644    3 1447   15   92  595 2574   19
  674] [1 0 0]
[   0    0    0    0    0    0  228 1040    9   17  436  173  235   43
 8103] [1 0 0]
[   0    0    0    0    0 2720   98  304  669 8104 1642   54 1020 1313
  601] [1 0 0]
[  0   0   0   0   0   0  39 437  59   8  47 143 211 260  19] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0    2
 1454] [0 0 1]
[   0    0    0    0    0    0   65 2263  284  377  928  109  372    9


 1282] [0 1 0]
[   0    0    0    0  326  386   41  304   57   89 1292  114   18   85
 3043] [1 0 0]
[   0    0    0   33    1   10   26   54  177   38    1 2697   59    1
 1396] [1 0 0]
[   0    0    0    0 3111  218 4465 2676   83   29    9    4   48   16
  146] [1 0 0]
[   0    0    0    0    0    0   46    1 2008   29   51 2099    2   46
    4] [0 0 1]
[  0   0   0   0   0   0   0   0 120 803 141 816 391   9  11] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0 482] [0 1 0]
[  0   0   0   0   0   2   5 979   1  32  38 760 999 219   9] [1 0 0]
[   0    0    0    0    0    0    0    0 1190    4   29  959   77 8167
  299] [1 0 0]
[   0    0    0    0    0  239   53   33    1   38  413    1 2611   42
  135] [1 0 0]
[   0    0    0    0    0    0    0    0    0   82  167   16  260  533
 8168] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0  76  27 586 114 268] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 203   8] [1 0 0]
[   0    0    0    0    0    0   

[  0   0   0   0   0   0   0   0   0   0   0   0 104 422  24] [1 0 0]
[   0    0    0    0    0  724   71  221 8319 8320 1261  864  480 8321
  196] [0 1 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 91] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0 370 560 123 124] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   2 143 286  25] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 123 124] [0 1 0]
[  0   0   0   0   0   0   0   0   0  64  67 294 183  40  91] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0 8322  378
 4225] [0 0 1]
[   0    0    0    0    0  493 4138  140    1  236  341   70  130  973
  437] [1 0 0]
[   0    0  741   68    4  436 8323 8324  181  562 1196  406   42 1077
  224] [1 0 0]
[   0    0    0 1849  449    6    3  419  187   43 2298 1355   93  507
 2119] [1 0 0]
[   0    0    0    0    0    3  135  476   17   10  196  512 4067  536
 1100] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0 934   1  33   1] [1 0 0]
[   0    

 3201] [1 0 0]
[   0    0    0    0    0    0    0    0    1    1  150 1561   57 8383
  447] [1 0 0]
[  0   0   0   0   0   0   0   0   0 856 252  79  66 786 290] [1 0 0]
[   0    0    0    0    0    0    0   15    3 1724 4492 2162 8384 8385
  113] [1 0 0]
[   0    0    0    0    0    0    0  340 1749   10  678  545   53  419
    1] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0  27   1 847 657   8] [1 0 0]
[   0    0    0    0    0    9    4  197   13   93  247   60  198 2453
   87] [1 0 0]
[   0    0 1877  615  686 8386   43  187  115  615  515   54   17   70
  459] [0 1 0]
[   0    0 8387 8388 1086 8389 4436  119 3270   15  441 8390 3010  574
 8391] [1 0 0]
[   0    0  283    3   95   75  128  241  202  385 1947   41 8392   21
   14] [1 0 0]
[   0    0    0    0    0    0    0    0  197    4 1095  240  215  238
  536] [1 0 0]
[  0   0   0   0  12 405  63 466 103 132 103  13  10 362 290] [1 0 0]
[   0    0   77  273  537 2772  273  603    1  808   61 4493    4 4493
   22] [1 0 0]
[

    4] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0  12 107  18  35   8] [1 0 0]
[   0    0    0    0    0   30   29 1736  154    1    6    3    6    1
 8445] [1 0 0]
[  0   0   0   0   0   0  26 183  40   1 324  19 653  97  69] [1 0 0]
[  0   0   0   0   0   0   0   0   1 456  32 223  22  11 354] [1 0 0]
[   0    0    0    0    0    0    0    0  353   72 8446  152 8447 3428
 8448] [1 0 0]
[   0    0    0    0    0   49 1564  592  352  240  240  114   46    9
    4] [0 0 1]
[   0    0    0    0    0    0    0  168  176  261  427  126    1 8449
  746] [1 0 0]
[   0    0    0    0    0 2420  249    9    4  227 2101   13  272   14
  568] [1 0 0]
[   0    0    0    0    0    0    0  138 8450 2101 1738 1263   41 3168
  355] [1 0 0]
[  0   0   0 112  11 151 232  24 633  36 629 228 534  11 151] [0 0 1]
[  0   0  16   8 324 356  17  47  44  43 365 116  99  62  38] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0   18   19  429 1971
  663] [

[  0   0   0   0   0   0   0   0   0  25   1 307 765  36 463] [0 0 1]
[   0    0    0    0    0    0    0    0    0  224   63   22  248   43
 2219] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0  38 433 309] [0 1 0]
[   0    0    0    0    0    0    0    0    0  321 8524 1611 1585 3835
 3929] [0 1 0]
[  0   0   0   0   0   0   0   0   0   9   4 197 197  83  30] [1 0 0]
[   0    0    0    0    0   61 1034  352  174  399   20   26   10   30
  367] [1 0 0]
[   0    0    0  195  237  133  353   53 1783   81  636 4223 4224    7
  364] [1 0 0]
[   0    0    0  355  296  209  782  164   28 1597  434   14 8525  106
  306] [1 0 0]
[   0    0    0    0    0    0    0    0   11  374  634  114 1670    1
  257] [1 0 0]
[   0    0  235  249 8526 2709  905  700 4505  566 1135 4505  566 1983
  106] [1 0 0]
[   0    0    0    0    0    0    0    0   26 8527   81  491 2640  313
  485] [0 1 0]
[   0    0    0    0    0    0    0    0  125   84 3059  669    1  237
   57] [1 0 0]
[   0    0    0 

  353] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    0  709 1330
 1037] [0 0 1]
[   0    0    0    0    0    0    0    0    0  199  425   68   99  215
 1108] [1 0 0]
[  0   0   0 636  59  45   1   7  26  10   1   6   3  13 103] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0  18 149  36 237] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0 70 43  5  1  1] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  101  799 1476    6
    3] [1 0 0]
[   0    0    0    0  219  428  334    1  182 1452  430  285 3159 1503
 1587] [1 0 0]
[   0    0    0    0    0    0    0   93  147   32  121  386   10  771
 1638] [1 0 0]
[   0    0    0    0    0    0    0    5   37 4368  200  244    1   42
  139] [1 0 0]
[  42 1088   21 1711  423   54  615  459  171  923   93   33  113  466
  817] [0 0 1]
[   0    0    0    0    0    0    0 1256 1357   58 8582 2264  167   72
 8583] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   2 463] [0 0 1]
[  0   0   0   0   0   0   0   0

  756] [0 0 1]
[  0   0   0   0   0   0   0 267 816 923   8 134 255  87  14] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 191   3   6] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 213 919 130] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0  11  12 255] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 941 941 941] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0 573  51 402 241 839] [0 1 0]
[   0    0    0    0    0 3561  120  954   59   17   23  234  179   16
   10] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0   16  169  461
 1558] [0 1 0]
[   0    0    0    0    0    0 8643 1456   20   35   75    1  806 2280
  983] [0 0 1]
[   2   91 4514 4366  929 8644   58    8 1405 1650 2287 2288 1650 2260
 2261] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0 219 230  19  62] [0 0 1]
[   0    0    0    0    0    0    0    0    2  376 2519 1376 2301 1082
  165] [0 0 1]
[   0    0    0    0    0    0    0    0  436 4515   36 2228   22

[  0   0   0   0   0   0   0   0   0 157 384 103  28  13   7] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   2  71  25 104  66] [1 0 0]
[   0   26  183  190  289  136   17  333   12  437   17  992  136 1293
   21] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0   23  371  257  392
 1651] [0 1 0]
[  0   0   0   0   0   0 605 174 156  75  14  20  35  23 433] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 312   2] [0 0 1]
[   0    0    0    0    2   62  326 1096 1541  443  270  321   13  638
 4301] [1 0 0]
[   0    0    0    0    0    0    0 1120 2548  174 1394  259   53   75
   14] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0 1170 3292  130
  166] [1 0 0]
[   0    0    0    0    0    0    0   26  158   10  116   36   18 2293
  593] [1 0 0]
[   0    0    0    0    0    0    0   49  662 2522   32  490  366   49
  116] [1 0 0]
[  0   0   0   0   0   0 193   1 315 547 190   1 217 200 111] [0 1 0]
[   0    0    0    0    0    0    0    0    0  2

  450] [0 0 1]
[   0    0    0    0    0    0    0    0    0 1120  823    2  629    4
   95] [0 0 1]
[   0    0    0    0    0    0 4222    9 8811  408 2595    9 1913  879
 2659] [0 0 1]
[   0    0    0  213  586  114  268 2672  349 3250 3238 4528 2285   18
   44] [0 1 0]
[   0  201   81 1013 3565  185 1121 3008 2674   96  852  414  185  693
 8812] [1 0 0]
[   0    0    0    0    0 4461    3   13   28  169    9  104  102  533
 2207] [1 0 0]
[   0    0    0    0    0    0   47  122  875   76  203   99   36 2040
  345] [1 0 0]
[   0    0    0    2   46    9    4   18  269 2283   96  868  198 2217
  450] [0 0 1]
[   0    0    0    0    0  100   20   12  324  528 2521  286  325   22
 1059] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 163 118   2] [0 0 1]
[   0    0    0    0    0    0    0    1  131  691 2596 1428   26   89
 1552] [1 0 0]
[   0    0    0   85  266 3242   21    1  352  701   10 1167 3555  701
    1] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0  73  16 949 37

 1724] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0 2155 2480   32
    2] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0   15    3   53  440
 2530] [1 0 0]
[   0    0    0    0    0    0    0    0    1   62   58   31 2742   89
  152] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 551 368] [1 0 0]
[  0   0 159 508  17 283 456  61 238 323 804  29  51  25 177] [1 0 0]
[   0    0    0    0    0    0   90  428  142  648    6  250  495 8910
 3272] [1 0 0]
[   0    0    0    0    0  226  243  375  129  207   49  262  521 3895
  478] [0 1 0]
[   0    0    0    0    0    0    0    0   34 2371 8911 2053 2073 8912
 8913] [0 1 0]
[   0    0    0    0  628 2735   57  363  342   84  169 1163   55   15
   53] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0 8914  134 1593   14
 1182] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    0  263  290
 1787] [0 1 0]
[   0    0    0    0    0    0  859    1  129   87   16  158 8915   49


[   0    0    0    0    4  160  106 1370 1606  838  549    1   12    5
   80] [1 0 0]
[   0    0    0    0    0    0    0   41  244 2080 1298   25   36  607
 2081] [0 0 1]
[  0   0   0   0   0   0  50 446   9 104 291  50 256 147  84] [1 0 0]
[   0    0    0   22  191    9    4  191 1021  930   79  531 1067  406
  438] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0 1510 1073   22
 1793] [1 0 0]
[  0   0   0   2  46   1 412 233 140  46 227 552 244 412 267] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0 865   4 122  31] [0 1 0]
[  0   0   0   0   0   1  12   5 192 170 295 378  47  19  19] [1 0 0]
[   0    0    0    0   16 2172   39   35   88  500  235   29  570   38
    1] [1 0 0]
[   0    0    0    2  944   84   30  484  591  880  975 2124 2842  659
   56] [0 0 1]
[  0   0   0   0   0   0  90   8 644 829  54 419 498   8 961] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0 15 14] [0 0 1]
[   0    0    0    0    0    0    0  158  114 1509  132 2051    1  961
  268] [

 9172] [0 1 0]
[  0   0   0   0   0   0   0   0 201 375 129 207  35 386  41] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0  174  156 4541  872
  671] [0 1 0]
[  0   0   0   0   0   0 112 311   6 904  25  43 104 391   9] [1 0 0]
[   0    0    0    0    0   31  740 1126  262 2266    3   55   14 1556
   87] [1 0 0]
[   0    0    0    0    0    0    0    0   30 1475   10  732   41   42
 1032] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 1 0]
[   0    0    0    0    0    0    0    0   16  157   11  597 1943  965
 1194] [0 1 0]
[   0    0    0  616   12    3   14  140  774  546  225 1967  516  546
 1539] [1 0 0]
[   0    0    0    0    0    0    0   18   40  144  881  691 1239  474
    8] [1 0 0]
[   0    0    0    0    0    0    0    0    0  792 1417 1169 2505 9173
  232] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0  34 424] [0 0 1]
[   0    0    0    0   95 1928   26   10  318  627   26  434    7   26
 2281] [1 0 0]
[  0   0   0   0   0   0   0   0   0 267 160 18

[  0   0   0   0   0  31 164 249  74 396 446  81   9 104 185] [1 0 0]
[   0    0    0    0    0  523 1116    7  787   57 1633  138 9224  751
  120] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 50] [0 1 0]
[   0    0    0    0    0 1003 3396 1335  115  131   79   30   24  131
   40] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0 1176  291   18
   44] [1 0 0]
[   0    0    0    0    0    0    0    0 1074  824  195 1258  921 2005
  206] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0   73   49 9225
 2157] [0 1 0]
[   0    0    0    0    0  665  162   39   53  726  101 1714  365 9226
   39] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  287 1623 1408  241
  480] [0 1 0]
[   0    0    0    0    0  384    3  347   15 4130   43  122  145 1319
   92] [1 0 0]
[   0    0    0    0  734    2 9227 1052  658    8  637    3  205 2155
 2480] [0 0 1]
[   0    0    0    0    0  221  144  553  182  134  255   14 9228  255
 1028] [1 0 0]
[   0    0    0

[   0    0    0    0   50  130   67  991   90  404 1001  677 1948 3105
 3972] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0  223   19   36  256
 1079] [0 1 0]
[  0   0   0   0   0   0 404 403 838 772  13  47 102  31 120] [1 0 0]
[   0    0    0    0    0    0    0    0  164  282  989 9301  466   42
   42] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0  66 399  66  54] [1 0 0]
[  0   0   0   0   0   2 252  98   1   6 313   6  29 149 589] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0 1360    1 9302
  323] [1 0 0]
[   0    0    0    0    0    0    0    0    0  384   19  270   87   14
 9303] [1 0 0]
[  0   0   0   0   0   0   0   0 100  24 106  79 119   5  37] [0 1 0]
[   0    0    0    0    0   13   88    3  269 2283 1598  324   17   35
   17] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0 3213  925  224  123
  124] [1 0 0]
[   0    0    0    0   11    1  256  147 1786   12  288  150 9304 2381
  243] [0 1 0]
[   0    0    0    0    0    0  

[   0    0    0    0    0    0    0    0    0    0    0    0    0 3544
 4434] [0 1 0]
[   0    0    5   80    1 2471  111   17    1   52  897 2471  588    1
 2471] [1 0 0]
[   0    0   32 9469   27    1  200    7   17   42    3   33    1 9470
   48] [1 0 0]
[   0    0    0  195   20 3202 1634 9471   70    1  209 1229  510    5
   37] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   0  91 369  67] [0 1 0]
[   0    0    0    0  840  203  183  278  949 1328    1  336  103 9472
   11] [1 0 0]
[   0    0    0    8 4514   16    8  929 2007 2287 2288 2007 2260 2261
 2007] [0 1 0]
[   0    0    0  215  214 1995   11  421   29   51  106   25   22 1183
  367] [1 0 0]
[   9    4 1150 3364  119    6    5   80   10   54   19 4332  119    6
    5] [1 0 0]
[   0    0    0    0    0  349  988   88   28   13   45  107  235  349
 4546] [1 0 0]
[   0  225 1964 4522  512 1146  169 9473   16 2583 3194   16    8  801
    4] [1 0 0]
[   0    0    0    0  179   81    9 2805  576    9    6    5  495 2266

Saving our features and classes data

In [19]:
from numpy import savetxt
savetxt('features.csv',features,delimiter=',')
savetxt('classes.csv',classes,delimiter=',')