IMPORT LIBRARIES

In [1]:
import numpy as np
import pandas as pd

READ DATA

In [2]:
data  = pd.read_csv("tweets.csv")
data = data.sample(frac=1).reset_index(drop=True)
data.head()

tweet_id airline_sentiment  airline_sentiment_confidence  \
0  568549060103135232          positive                        1.0000   
1  568092350355865600          negative                        1.0000   
2  570116329694310400          negative                        1.0000   
3  569911816937033728          negative                        1.0000   
4  570012789479055360          negative                        0.6712   

     negativereason  negativereason_confidence         airline  \
0               NaN                        NaN          United   
1        Can't Tell                     0.6821          United   
2       Late Flight                     1.0000        American   
3  Cancelled Flight                     1.0000  Virgin America   
4       Late Flight                     0.6712      US Airways   

  airline_sentiment_gold             name negativereason_gold  retweet_count  \
0                    NaN        annricord                 NaN              0   
1                    NaN       eatgregeat                 NaN              0   
2                    NaN         Steponme                 NaN              0   
3                    NaN  AlisonK33774854                 NaN              0   
4                    NaN         theF4rns                 NaN              0   

                                                text  \
0           @united @annricord Great! Appreciate it😊   
1  @united - with airport self checkin your only ...   
2  @AmericanAir after running from one flight, be...   
3  @VirginAmerica I like the TV and interesting v...   
4  @USAirways  has me on my toes whether I'm goin...   

                   tweet_coord              tweet_created  \
0                          NaN  2015-02-19 15:13:53 -0800   
1  [29.98605741, -90.25189405]  2015-02-18 08:59:05 -0800   
2  [32.91792297, -97.00367737]  2015-02-23 23:01:39 -0800   
3                          NaN  2015-02-23 09:29:00 -0800   
4                          NaN  2015-02-23 16:10:13 -0800   

            tweet_location                user_timezone  
0                  Canmore  Mountain Time (US & Canada)  
1                      NaN   Eastern Time (US & Canada)  
2  Moore, OK & Woodway, TX   Central Time (US & Canada)  
3                      NaN                          NaN  
4                      USA   Eastern Time (US & Canada)

EXTRACTING LABELS AND TWEETS

In [3]:
reviews = np.array(data['text'])
labels = np.array(data['airline_sentiment'])
reviews

array(['@united @annricord Great! Appreciate it😊',
       "@united - with airport self checkin your only option I'm now your employee. Training was a bitch. Send my paycheck asap.",
       '@AmericanAir after running from one flight, because we had 10 mins, to our next flight, we then sat on our plane for an hour.',
       ...,
       '@AmericanAir  They said it works 80-90% of the time, DFW security entrance C26. Before/after pre-check, whereas I paid for the service.',
       '@USAirways Strike Three!!! You guys suck!!!',
       '@AmericanAir I have almost 3 million miles w u so I am loyal to u.  When r u going to reciprocate?  What a joke'],
      dtype=object)

In [4]:
labels

array(['positive', 'negative', 'negative', ..., 'neutral', 'negative',
       'negative'], dtype=object)

CLEARING PUNCTUATIONS , HYPERLINKS , AND NUMBERS

In [5]:
from string import punctuation
def clean(words):
  #  punctuation = '@!"#$%&'\()*+,-./:;<=>?[\\]^_`{|}~'
    nword = []
    for word in words:
        if word[0] not in punctuation and word.find('http')==-1 and any(char.isdigit() for char in word)==False:
            #word = word.replace(punctuation, ' ')
            for pun in punctuation:
                word = word.replace(pun,'')
                word = word.lower()
                word = word.replace(" s "," ")
                
            nword.append(word)
    
    return nword

IMPORT SPACY's ENGLISH 

In [6]:
import spacy
spacy.prefer_gpu()
nlp = spacy.load("en_core_web_sm")

FUNCTION FOR LEMMATIZATION

In [7]:
def lemma(sentence):
    doc = nlp(sentence)
   # print(doc)
    sent = " ".join([token.lemma_ for token in doc if token.is_stop==False])
   # print(sent)
# Extract the lemma for each token and join
    return sent

LEMMATIZING AND CLEANING 

In [8]:

revs = []
for re in reviews:
    #print(re)
    re = lemma(re)
    re = re.split()
    rn = clean(re)
    revs.append(rn)
    #print(rn)
revs

[['great', 'appreciate', '😊'],
 ['airport',
  'self',
  'checkin',
  'option',
  'employee',
  'training',
  'bitch',
  'send',
  'paycheck',
  'asap'],
 ['run', 'flight', 'min', 'flight', 'sit', 'plane', 'hour'],
 ['like',
  'tv',
  'interesting',
  'video',
  'disappointed',
  'cancel',
  'flightled',
  'flight',
  'flight',
  'go',
  'jfk',
  'saturday'],
 ['toe', 'go', 'flight', 'boston', 'tonight'],
 ['time',
  'tweet',
  'tell',
  'horrible',
  'attendant',
  'flight',
  'lga',
  'feel',
  'jail'],
 ['ewr',
  'ppl',
  'tell',
  'day',
  'monday',
  'layover',
  'loc',
  'ref',
  'tho',
  'help',
  'appreciate'],
 ['flight',
  'aa',
  'botch',
  'weather',
  'delay',
  'point',
  'absurdity',
  'pay',
  'fly'],
 ['thank', 'quick', 'response', 'daily', 'wait', 'day'],
 ['land', 'ric', 'right', 'leave', 'atl', 'pick', 'delta', 'maybe'],
 ['wait', 'flt', 'chicago', 'aircraft', 'leave', 'buffalo'],
 ['complt',
  'incompetence',
  'flt',
  'delay',
  'pln',
  'lnde',
  'nite',
  'inter

making an array of all words

In [9]:
all_words = []
for re in revs:
    for word in re:
        all_words.append(word)
        
print(all_words)

['great', 'appreciate', '😊', 'airport', 'self', 'checkin', 'option', 'employee', 'training', 'bitch', 'send', 'paycheck', 'asap', 'run', 'flight', 'min', 'flight', 'sit', 'plane', 'hour', 'like', 'tv', 'interesting', 'video', 'disappointed', 'cancel', 'flightled', 'flight', 'flight', 'go', 'jfk', 'saturday', 'toe', 'go', 'flight', 'boston', 'tonight', 'time', 'tweet', 'tell', 'horrible', 'attendant', 'flight', 'lga', 'feel', 'jail', 'ewr', 'ppl', 'tell', 'day', 'monday', 'layover', 'loc', 'ref', 'tho', 'help', 'appreciate', 'flight', 'aa', 'botch', 'weather', 'delay', 'point', 'absurdity', 'pay', 'fly', 'thank', 'quick', 'response', 'daily', 'wait', 'day', 'land', 'ric', 'right', 'leave', 'atl', 'pick', 'delta', 'maybe', 'wait', 'flt', 'chicago', 'aircraft', 'leave', 'buffalo', 'complt', 'incompetence', 'flt', 'delay', 'pln', 'lnde', 'nite', 'internet', 'poor', 'svc', 'expect', 'u', 'price', 'flight', 'oahu', 'good', 'friend', 'look', 'like', 'today', 'consecutive', 'delay', 'flight', 

**tokenizing unique words**


In [10]:
from collections import Counter
counts = Counter(all_words)

sorted_counts = sorted(counts,key=counts.get,reverse=True)
word_to_int = {word:ii for ii,word in enumerate(sorted_counts,1)}

sz = len(word_to_int)

coded_revs = []
for review in revs:
    coded_revs.append([word_to_int[word] for word in review])

coded_revs


[[46, 125, 589],
 [41, 1421, 489, 166, 161, 964, 2296, 50, 4547, 456],
 [225, 1, 53, 1, 55, 14, 3],
 [31, 412, 1422, 694, 299, 5, 37, 1, 1, 24, 95, 680],
 [4548, 24, 1, 227, 110],
 [7, 172, 23, 257, 129, 1, 349, 234, 4549],
 [210, 570, 23, 19, 375, 510, 2297, 2680, 813, 8, 125],
 [1, 86, 4550, 51, 6, 148, 4551, 61, 11],
 [2, 364, 84, 927, 13, 19],
 [134, 1653, 85, 42, 475, 262, 457, 278],
 [13, 119, 251, 541, 42, 928],
 [4552, 929, 119, 6, 4553, 4554, 2681, 847, 248, 716, 249, 47],
 [322, 1, 4555, 25, 211],
 [58, 31, 32, 2298, 6, 1, 465, 3299, 132, 11, 4556, 443],
 [78, 185, 1798, 23, 10, 70, 6, 78, 289, 681, 3300, 36, 29],
 [264, 139, 150, 3301, 78, 1334, 142, 695, 10],
 [2299, 9, 4, 1799, 3302, 5, 1184, 1, 624],
 [18, 2300, 220, 2],
 [138, 20, 35, 176, 349, 4557, 26, 10, 777, 879, 3303],
 [46, 9, 4, 2],
 [42, 53, 4558],
 [880, 36, 682, 2301, 1008, 296, 27, 1008, 4559, 3304],
 [881, 63, 296],
 [30, 29, 1654, 154, 1, 6, 3, 6, 1, 4560],
 [23, 148, 47, 778, 47, 11, 187, 110, 47, 5, 37, 2

In [11]:
print(sz)

9481


ENCODING LABELS

In [12]:
classes=[]
for lab in labels:
    if lab=='positive':
        classes.append([0,0,1])
    elif lab=='neutral':
        classes.append([0,1,0])
    else :
        classes.append([1,0,0])
classes

[[0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [1, 0, 0],
 [0,

MAX AND MIN LENGTH OF REVIEWS

In [13]:
review_lens = Counter([len(x) for x in coded_revs])
print("Zero-length reviews: {}".format(review_lens[0]))
print("Maximum review length: {}".format(max(review_lens)))

Zero-length reviews: 70
Maximum review length: 43


In [14]:
for i in range(44):
    print(i,review_lens[i])

0 70
1 531
2 659
3 922
4 1019
5 1100
6 1304
7 1344
8 1487
9 1587
10 1517
11 1159
12 880
13 520
14 285
15 133
16 62
17 33
18 14
19 6
20 4
21 0
22 0
23 1
24 0
25 0
26 0
27 1
28 0
29 0
30 1
31 0
32 0
33 0
34 0
35 0
36 0
37 0
38 0
39 0
40 0
41 0
42 0
43 1


REMOVING REVIEWS WITH 0 LENGTH

In [15]:
print('Number of reviews before removing outliers: ', len(coded_revs))

## remove any reviews/labels with zero length from the coded_revs list.

# get indices of any reviews with length 0
non_zero_idx = [ii for ii, review in enumerate(coded_revs) if len(review) != 0]

# remove 0-length reviews and their labels
coded_revs = [coded_revs[ii] for ii in non_zero_idx]
classes = np.array([classes[ii] for ii in non_zero_idx])

print('Number of reviews after removing outliers: ', len(coded_revs))

Number of reviews before removing outliers:  14640
Number of reviews after removing outliers:  14570


In [16]:
extra_neg=[]
x=4000

FUNTION TO PAD REVIEWS (right)

In [17]:
def pad_features(reviews_ints, seq_length):
    ''' Return features of review_ints, where each review is padded with 0's 
        or truncated to the input seq_length.
    '''
    
    # getting the correct rows x cols shape
    features = np.zeros((len(reviews_ints), seq_length), dtype=int)

    # for each review, I grab that review and 
    for i, row in enumerate(reviews_ints):
        features[i, -len(row):] = np.array(row)[:seq_length]
    
    return features

In [18]:
seq_length = 15

features = pad_features(coded_revs, seq_length=seq_length)

In [19]:
for i in range(len(coded_revs)):
    print(features[i],classes[i])

[  0   0   0   0   0   0   0   0   0   0   0   0  46 125 589] [0 0 1]
[   0    0    0    0    0   41 1421  489  166  161  964 2296   50 4547
  456] [1 0 0]
[  0   0   0   0   0   0   0   0 225   1  53   1  55  14   3] [1 0 0]
[   0    0    0   31  412 1422  694  299    5   37    1    1   24   95
  680] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0 4548   24    1  227
  110] [1 0 0]
[   0    0    0    0    0    0    7  172   23  257  129    1  349  234
 4549] [1 0 0]
[   0    0    0    0  210  570   23   19  375  510 2297 2680  813    8
  125] [1 0 0]
[   0    0    0    0    0    0    1   86 4550   51    6  148 4551   61
   11] [1 0 0]
[  0   0   0   0   0   0   0   0   0   2 364  84 927  13  19] [0 0 1]
[   0    0    0    0    0    0    0  134 1653   85   42  475  262  457
  278] [1 0 0]
[  0   0   0   0   0   0   0   0   0  13 119 251 541  42 928] [1 0 0]
[   0    0    0 4552  929  119    6 4553 4554 2681  847  248  716  249
   47] [1 0 0]
[   0    0    0    0    0    0  

 3323] [0 1 0]
[   0    0    0    0    0    0    0    8   11  264   14 4607  185 3324
  964] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0  73  24 284   3] [0 1 0]
[   0 1268  438  193   11  445 4608  120  381  644   28 2691  627  328
 4609] [1 0 0]
[  0   0   0 119 210 180 645   4 513   1 129   1  25 156  19] [0 0 1]
[ 103   17 4610    1   33  112  134  168 3325   17  417  258   13   20
  328] [1 0 0]
[   0    0    0    0    0 1661 1809   63  573 1662    1   71  880 1519
  329] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0 1427
 4611] [0 1 0]
[   0    0    0    0    0    0    0 3326 2023  402  279 1520  933 1129
  146] [1 0 0]
[   0    0    0    0    0    0  608  240  697   71  185 1277 1810 4612
 4613] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0  13  75 820 307] [1 0 0]
[  0   0   0   0   0   0   0   0   0  48   7 414 126 173  61] [1 0 0]
[  0   0   0   2   6   1   3  38 154   1 198   9   4 667 270] [1 0 0]
[  0   0   0   0   0   0   0   0 

  127] [0 1 0]
[  0   0   0   0   0   0 421  30 326   3  62 211  30  13 134] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0  16 692   1  27  50] [0 1 0]
[  0   0   0   0   0   0   0   0   0 174 706 148 150 847 889] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0 113 940 441 527] [0 1 0]
[   0    0    0    0    0    0    0 1199   35  189   97  247   28    4
  198] [1 0 0]
[   0    0    0    0    0    0    0    0    0   53  210   78  179 3380
  235] [1 0 0]
[  0   0   0   0   0   0 145 301  77   6  83 144  28 122 594] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0  16   9   4 978 170] [0 1 0]
[   0    0    0    0    0    0    0 1026  439   77  672    2  198   22
  469] [1 0 0]
[   0    0    0  300 4722 4723  173    1   20   35  150   75  673  605
    7] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0  289
 1290] [0 1 0]
[   0 2733   11  432   33 1423  213    1   17  610  271  348 1291  213
    1] [1 0 0]
[ 164    1  228  653  634  831  426  305  423 108

  523] [1 0 0]
[  0   0   0 109  15  53  23  24 142   1 131  87 175   9   4] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[   0    0    0    0  142   27    1 1266  261  582   17   48  293    1
 2061] [1 0 0]
[   0    0    0    0    0    0    0 4780  182  983   10  185   36  341
 2685] [1 0 0]
[   0    0    0    0    0    0    0    0    0  212   18   70    1  531
 1146] [0 1 0]
[   0    0    0    0    0    2 1362 1854  728  171    1  150  284    3
  581] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0 144 780 189   8  34] [1 0 0]
[  0   0   0   0   0   0  26   1 191 538 498   1 239  35 120] [1 0 0]
[   0    0    0    0    0  146 4781   26  358   26 2062   59   36  742
  439] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   2  64 264 709] [0 0 1]
[   0    0    0    0    0    0    1    5   80   15   45  381 2304 1090
  285] [1 0 0]
[  0 138   9 716  99 733 126   1 682 142 643  72 521   9 785] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0 369] [0 1 0]
[   0    

 2090] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  1 52  5 37] [1 0 0]
[   0    0    0    0    0    0    0    0    0  246   79    1 1849  820
   14] [1 0 0]
[   0    0    0    0    0    0   53  200 4866  100  100    7  186  503
 4867] [1 0 0]
[  0   0   0   0   0  18 142   1  18  27  28 632  27 175 473] [1 0 0]
[   0 1372   10 4868   10  208   56   10 1848 2776  551 1570  381    8
  756] [1 0 0]
[  0   0   0   0   0   0   0  73 279   5  37  17 115 170  68] [1 0 0]
[   0    0    0    0   18  144    9    4  159 1373  423   15 2385   16
    8] [1 0 0]
[   0    0    0    0    0    0    0    0   15    3   45  188  202 4869
 2777] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0 2778  339  408
   79] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0   58 1865   58
 3437] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   0   9   4 198] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0 34 91 67] [0 1 0]
[  0   0   0   0   0   0   0   1 462   5  37   1  18  17 381] [

  214] [0 1 0]
[   0    0    0    0    0  219  733 1089 4957 2353    1   90  621  132
 2110] [0 0 1]
[   0    0    0    0    0   58  398   11  380  595  507   22 1565 1101
 3487] [0 0 1]
[   0    0    0    0    0    0    0    0    0  774  833 2111   25   30
  609] [0 0 1]
[   0    0    0    0    0    0    0    0    0  254  558  624  841 1537
   76] [0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[   0    0    0    0    0    0    0    0  478   40  247  161 2411    9
 1715] [1 0 0]
[   0    0    0    0  368   15    1 2321  134  331    3    6 1164  346
   87] [1 0 0]
[   0    0 3488    1 4958  318   61  370  801  695   39  205  504  148
 3489] [0 1 0]
[   0    0    0 1716    1  129    1  492 2112  206   16  861  463   25
   74] [0 0 1]
[   0    0   14  236  209   53   20   71   40  109 2113  346 1273 1578
  130] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 734 444 867] [0 0 1]
[   0    0    0 1380  332  261    2  105   26   92  157    9    4 1132
 1063] [1 0 0]
[   0    0    0

   83] [0 1 0]
[   0    0    0    0    0    0    0   60  295  311   91 2750 1383  463
  463] [0 0 1]
[   0    0    0    0    0    0    0    0    2  243  157   21  383 4983
  136] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0  16  56  23 117 508] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0  72 731 258  13] [1 0 0]
[   0    0    0    0    4  168 1882    3  310   13   20  377   38   98
 1882] [1 0 0]
[   0    0    0  831  905   22   79  332  483  316  419    9    4 4984
 2418] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0 4985    4 4986
   32] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    0  395 1883
  677] [0 1 0]
[   0    0    0    0    0    0  661   64   64 2718   21  694  136 1884
 4987] [0 0 1]
[  0   0   0   0   0   0   0   0   0  18  44   1  17 202 912] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0   30  308  527   51
 1822] [0 1 0]
[   0    0    0    6 2819  913 1008   46   36   34   82  103   55   14
 4988] [1 0 0]
[

 1320] [1 0 0]
[   0    0    0    0    0  472 5065  321  629  677 1243  295 2435  371
  427] [1 0 0]
[   0    0    0    0    0    7  121   20 1849  706  302   14 1280   53
    6] [1 0 0]
[   0    0    0    0    0    0  472    9    4 1907   36   41  128   16
  446] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0  92  57 208   1  52] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0 268 213   1 180 340] [1 0 0]
[   0  349  462    5   37   28  669    8 1475   96   20 1296  556  311
 2135] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0   75    7
 5066] [1 0 0]
[   0    0    0    0    5   37    6    1  131  207  114   56 2436  250
  509] [1 0 0]
[   0    0    0    0    0    0    0  396   47 1015 1602   74 1392   11
   69] [1 0 0]
[   0    0    0    0    0   18   99   44   22  421   11  111  679 1170
 3551] [0 0 1]
[   0    0    0    0    0    0  100  704 1206   21  412   11  176 2855
 3552] [0 1 0]
[ 0  0  0  0  0  0  0  0  0  0 

  384] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0 1689  348    1   23
   10] [1 0 0]
[   0    0    0    1    6    7   32    1 2153  970  176    3    6  376
 5178] [1 0 0]
[   0    0    0    0    0    0    0  829 2461 5179   12 2879 5180 5181
 5182] [0 1 0]
[   0    0    0    0    1  680 1468  209 1922  244 2880 1468   47  246
   27] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0  25 637] [0 0 1]
[   0    0    0    0    0    0    0  341 1738   10  670  544   53  417
    1] [1 0 0]
[  0   0   0   0   1   5 192  15 103 293  16   8  72  43  94] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0 872 222 123 124] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0 318   5   1  76  90] [0 1 0]
[   0    0    0    0    0    1    5   37  304   57  115 1043  370   51
    8] [1 0 0]
[   0    0    0    0    0    0    0    0 2154    5   80    1  284    3
   56] [1 0 0]
[   0    0    0    0    0    0    0    0  998 5183   57  213 5184 3597
   29] [1 0 0]
[   0    0    0  

  151] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  852  302  319 5223
   41] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0   65  169    8
 5224] [1 0 0]
[   0    0    0    0    0  727   72  224 5225 5226 1197  869  477 5227
  196] [0 1 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 25] [0 1 0]
[   0    0    0    0    0    0    0    0    0  764   75  273 2164  188
   90] [0 1 0]
[   0    0    0    0  354   78  179   68   68   39  122  636 1074  111
  106] [1 0 0]
[   0    0    0    0    0    0    0    0    0  140 5228  501 5229  718
 1035] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    0  178    1
 1140] [0 1 0]
[   0    0    0    0    0    0    0    0    0 2456   59    1  117   10
 2893] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0 15  3] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0  253   69 5230
 5231] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 705  56] [0 1 0]
[  0   0   0   0 125  12  15  1

  800] [1 0 0]
[  0   0   0   0   0   0  11   6 444  95 348  33 112   1 151] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
 5291] [0 0 1]
[   0    0    0    0    0    0    0    1 2477  685   53   89 5292 5293
 5294] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0 777] [1 0 0]
[  0   0   0 900 434  12  60   1   5  37 536   1 475   6 194] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0  278 1461
  204] [0 1 0]
[   0    0    0    0  115   16 5295  607   40   23  249  849  321 5296
  239] [1 0 0]
[  0   0   0   0   0   0   0   0 842   6   1  38  98 453   8] [1 0 0]
[   0    0    0    0    0 2904  897   44  897 2439 2905 2906   43 2178
 1459] [0 1 0]
[   0    0    0    0    0    0    0    0  101  108 1347  186  701   72
  323] [1 0 0]
[   0    0    0    5  192  213    1  319 3640  117    3  216 2179  508
   89] [1 0 0]
[   0    0    0    0    0    0    0    0    1 5297 5298   42  210   24
   29] [1 0 0]
[   0    0    0  

   20] [0 1 0]
[   0    0    0   23   66    1 1233  113    1 1282    5   37   12  152
  176] [1 0 0]
[   0    0    0  225   48 1047  205 1688 5325 2913  136 5326  217 1243
   85] [0 1 0]
[   0    0    0    0    0    0    0    0    0    1   24   12   14 5327
 3656] [1 0 0]
[   0    0    0    0    0    0    0    0    0 1475    2   58  398   72
  825] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   1  77   7 233  87] [1 0 0]
[   0    2   72   56   32  566 3657   25  893    5    1    1  128 5328
 3658] [0 0 1]
[ 0  0  0  0  0  0  0  0  0  0  0 66 13  3  1] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 60] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0 157] [0 0 1]
[   0    0    0    0    0    0    0    0    0  272  726  478   35 3659
 1477] [1 0 0]
[   0    0    0    0    0    1    5  192  619  293   49 1032  266  467
  122] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  216    1   76  639
 1254] [1 0 0]
[   0    0    0    0    0    0    0    0    0  

[  0   0   0   0   0   0   0   0 125 373  43   1   6 304 261] [1 0 0]
[   0    0    0   29   22  409 1148  116 1944  183   33    1    1  190
 1580] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0   83   14
 2374] [0 1 0]
[ 212  405   18  120   44   49 1164   28  276  433  836  116   99  133
  246] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 263 369  41] [0 0 1]
[  0   0   0   0   0   0   0 299 818 408 561  33   1   1 257] [1 0 0]
[   0    0    0    0    0    0    0    0    0   31  214  178   21 5415
    1] [0 1 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 67] [0 1 0]
[   0    0    0    0    0 1322 1032  146  260   14   55  103  384  310
   24] [1 0 0]
[   0    0    0    0    0    0    0    5    1    1 5416 5417 2941  504
   21] [1 0 0]
[   0    0    0    0    0    0    0    6    6 1117 1256   16  352 2925
  130] [1 0 0]
[   0    0    0  171  143 5418  412  180  871   95    1   93  147   12
   60] [1 0 0]
[   0    0 1713 3696  389  699 3696  114   11  

  546] [0 0 1]
[   0    0    0    0    0    0    0   65   40    8  582  234   31 1585
    9] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 6] [1 0 0]
[  0   0   0   2  40 717 114 533  93 147 317 217 904  86 318] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 441 372   2] [0 0 1]
[   0    0    0    0    0  219    9   13 2503  691  256 2805  964   16
  773] [1 0 0]
[   0    0    0    0    0    0  631 2203  985    1  547 2948  136  156
   19] [0 0 1]
[  0   0   0   0  29   9   4  88  65   7  32 169 144 334 381] [1 0 0]
[   0    0    0  133  501  267 5471 1612 1025   31   47 5472   58  208
   39] [0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[   0    0    0 5473 1117 1407   20  740 3713 5474  570   38    1   31
 1836] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0  91 670  67  82] [1 0 0]
[   0    0    0    0    0    0    0  132  348   86 1390  183   86  183
  157] [0 1 0]
[   0    0    0    0    0   63   27  549 2470 5475 5476 2504 2204  708
 3714] [0 0 1]
[  0   0   0   0   0   

   53] [1 0 0]
[   0    0    0    0    2 1809 5555  401  435   24    8 1474    1    5
   37] [0 0 1]
[  0   0   0   0 497 525   1   5  37 541 310  36 113  32  52] [1 0 0]
[   0    0    0    0    0    0   73 2963 2964   18  100 5556  369    1
  373] [1 0 0]
[   0    0    0    0    0    0 5557  420   51    6 2834  289  157   89
 5558] [1 0 0]
[   0    0    0    0    0    0 1165    1  447    2    3   33    1   71
  535] [1 0 0]
[  0   0   0   0   0   0   0   0   0 856 254  79  66 812 291] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0   91   11
 2965] [0 1 0]
[   0    0    0    0    0    0    0  146  371 2210   45    6   20   13
  128] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0   18  108  182 5559
 5560] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0 1035 1908  491 3742
 1763] [0 1 0]
[   0    0    0    0    0    0    0    0    0   54   10   99  151 2211
 1236] [1 0 0]
[  0   0   0   0   0  24  38  98   1  56   6  20  35  14 351] [1 0 0]
[

[   0    0    0    0    0    0    0    0    0    0    0 5628    6  301
 1144] [1 0 0]
[  0   0   0   0   0   0   0 208 107  97   8 379 131  87   1] [1 0 0]
[  0   0   0   0   0   0 195  41   8   9  12  23   1  42 953] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0 1681   15   45   27
    1] [1 0 0]
[   0    0    0    0    0    0    0    0   16  156   11  589 1853  982
 1240] [0 1 0]
[   0    0    0    0    0    0  259  171   64 2980 3766  724  831 1082
 3767] [0 1 0]
[  0   0   0   0   0   0   0   0  15   1 173  72 323  45 147] [1 0 0]
[   0    0    0    0    0    0    0    0  310    3  550 2531  735  852
  382] [1 0 0]
[   0    0    0    0    0    0   26 3768 2730  470  522 3730   95  612
    2] [0 1 0]
[   0    0    0    0    0    0    0    0  413  208  168   57 1179 5629
  108] [1 0 0]
[   0    0    0  182   51   57    7    5   80 1687    5   80 2186  100
 3757] [1 0 0]
[   0  230  560 5630  529  128   56  679  236 1310   38 1828 3769  647
 5631] [0 1 0]
[   0    0    0 

   63] [0 0 1]
[  0   0   0   0   0   0   1 113  79  55  14  13  66 385  13] [1 0 0]
[   0    0    0    0  615   38   98  274   38 3005 5704 2367    1  145
 5705] [1 0 0]
[   0    0    0    0    0    2   34   12  352 2836  915  264   93   86
  215] [0 0 1]
[   0    0    0    0    0    0   50  567  567  403  567  294 5706  243
 5707] [1 0 0]
[   0    0    0    0    0 1502 1484   19  147   55   14   95  103  732
   75] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 278 284 688] [0 1 0]
[  0   0   0   0   0   0   0   0   0   1 217   6 498 346 917] [1 0 0]
[   0    0    0    0    0 5708  288  940  853   63  652 3006  591 5709
  854] [0 0 1]
[   0    0    0    0    0    2  238 2919   58  398 5710  284  657  415
  179] [0 0 1]
[   0    0    0    0 3007   31  104  570   83 2544  150  749 3805   81
  546] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0   34
 3806] [1 0 0]
[   0    0    0 3807  275    4  299   32  495  326 1024  228   41  110
  984] [1 0 0]
[

 5754] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0 3409    1 3410
 3411] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    2   12  492  126
 3016] [0 0 1]
[   0    0    0    0    0    0  655  233 1124  231  826  139    7 1860
  261] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0 42  6] [1 0 0]
[   0    0    0    0    0    0    0    0    0  608   49 1041  616  580
    1] [1 0 0]
[   0    0    0    0    0 1250 1250 1516  173    7  905  895 5755  203
  965] [0 0 1]
[   0    0    0    0    0    0  374  191   47    5  192    1  118 3017
 1049] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0 1207 3600  186  101
  136] [0 0 1]
[  0   0   0   0   0   0   0   0   0 302 302 327 134 187 218] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 502  38  98] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  133   13  108    4
 5756] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  446 3581 5757  504
 5758] [1 0 0]
[   0    0    0 

[  0   0   0   0   0   0   0   0   0   0 287 647 155 251  93] [0 0 1]
[  0   0   0   0   0   0   0  64  87 282  76 259 146  64 478] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 158 213 245] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0  289  197  738
 1153] [1 0 0]
[  0   0   0   0   0   0   0   0   1  24   5  37  93 177 153] [1 0 0]
[   0    0    0    0  955  142 1414   10  411 1477 1414  958 1088   66
   26] [0 1 0]
[   0    0    0    0    0    0    0    0  235 5812   87    6  667  483
  485] [1 0 0]
[   0    0    0    0  179   51 3839   71  635   21   14   85  149   30
   99] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0 194 249 143 383] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0  308 5813 1610
 3840] [0 1 0]
[   0    0    0    0    0    0    0    0    1 1032 2529   18   44    1
 1032] [1 0 0]
[   0    0    0    0    0    0 2235 1136  283 5814 1466 5815 2959 5816
 5817] [0 1 0]
[   0   

[  0   0   0   0   0   0   0   0   0   0   0   0 202  36 473] [1 0 0]
[   0    0    0    0    0    0    0    0    0  882    1    6 1214  187
   97] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
 5878] [0 1 0]
[   0    0    0    0    0    0    0    0    0  153  903  174   11   22
 2917] [0 1 0]
[   0    0    0    0    0    0    6    3    3    1  366  584 1743  557
    3] [1 0 0]
[  0   0   0   0   0   0   0   1 952 152 169 130  28 155 411] [1 0 0]
[  0   0   0   0   0   0   0  23  13   7  13   3   3  24 235] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0 206 341 144   9   4] [1 0 0]
[   0    0    0    0 5879  720  564  402  290  720  614  137   48 1075
 1521] [1 0 0]
[   0    0    0    0    0    0    0    0    0   62   30   93 1259 1259
  222] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0  90 194] [1 0 0]
[   0    0    0    0    0  149 1811   54  521  173  599  353  241  240
 1291] [1 0 0]
[   0    0    0    0    0    0  313  195   59 58

 1049] [1 0 0]
[  0   0   0   0   0   0 226  39 288 242 150 532 709 135 455] [0 1 0]
[   0    2  706 1327   14   16  430 2788   33    1   46 5962  935 1014
 1853] [0 0 1]
[   0    0    0    0    0    0    0    0 1674   43   83  853  447 5963
 2020] [1 0 0]
[   0    0    0    0    0   64 5964 2540 2094   31 1081 5965 1110 3890
 5966] [1 0 0]
[   0    0    0    0   57   95  141  416   95 2468  216  976  349 2562
 5967] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0 300  67  36 338] [1 0 0]
[   0    0    0    0    0    0  139  976  731  408 1029   62 1714  554
    1] [1 0 0]
[  0   0   0   0   0   0   0   2  25 806  26 152  26  58   1] [0 0 1]
[   0    0    0    0    0    0    0    0  518    1  193  121  117   32
 1170] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0 239] [1 0 0]
[  0   0   0 138  20  35 404 110  20   6   1  83 308 964 670] [1 0 0]
[  0   0   0   0   0   0   0   0  30  18 297  65  24  62  30] [1 0 0]
[   0    0    0    0    0    0    0    0    0    

  224] [0 0 1]
[   0    0    0    0   86   25  231 6061    1    6   45  732 2946   79
   10] [1 0 0]
[   0    0    0  213    1 3891 1984  510  242 1034 3074  205  242    1
 3924] [1 0 0]
[   0    0    0    0    0    0    0    0   73 1879  909   12  385  351
  193] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0    0 6062  123
  124] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 117   2  91] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0 162] [0 1 0]
[   0    0    0    0    0    0    2 3455  185  168   46    4 2581  110
  125] [0 0 1]
[   0    0    0  268    1    5   80  810  152  498   15 1004  303   48
  102] [1 0 0]
[   0    0    0    0    0    0    0   73   17 3925   82  108   22    7
  469] [1 0 0]
[   0    0    0    0    0    0    0 3009 6063   31 1913  752   26   66
 6064] [0 1 0]
[   0    0    0    0    0    0    0    0  300   38 1372    1  122  208
   39] [0 1 0]
[  0   0   0  46 231  32 448  59 270   2 947 141  96  38   1] [1 0 0]
[

 1345] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   3  15 715  36] [1 0 0]
[   0    0    0    0    0    0    0    0  156  927    1 1077 1554 6115
  766] [0 1 0]
[   0    0    0    0    0    0 2371  575  114  241  614   22  944  235
 6116] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 66] [1 0 0]
[   0    0    0    0    0    0  302 1770 1327   14  191    3  121  287
  613] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0 1265    9    4   74
 6117] [0 0 1]
[   0    0    0    0    0    0    0    0   83 1198  298   59  177  559
   86] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0  53 285] [0 1 0]
[   0    0    0    0    0    0    0    2  994  680  150 1369 6118 1018
  746] [0 0 1]
[  0   0   0   0   0   0   0   0 308   8  20  35  18 158   1] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0 618 486 194  26] [0 0 1]
[   0    0    0    0    0    0    0    0   55 1677   53   38   98  545
  450] [1 0 0]
[   0    0    0    0    0    0  275 6119   40  1

  108] [1 0 0]
[   0    0    0    0  182   16 6203 2259 2127 1773  220   26  173  840
   82] [1 0 0]
[   0    0    0    0    0    0    0   18 1780 1397   44  259    1  322
    8] [0 1 0]
[   0    0    0    0 1957  441    1   75   17  167   33  112   55  100
  187] [1 0 0]
[  0   0   0   0   0   0   0 294   3  33   1  42 113 650 658] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1] [1 0 0]
[  0  18 250   1  18  27 393  39 376 323   2  50 289  30 175] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0 2404  107   64
   81] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0 280   7   1 270] [1 0 0]
[  0   0   0   0   0   0   0   0   0 388   7  22 480 245 961] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0  998 1894 3972
  161] [1 0 0]
[   0    0    0    0  574  321 1260 3973  172  740   17 1392  394  432
    9] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   0 246  15  87] [1 0 0]
[   0    0    0    0   64 1452 6204  206  389  136   71 2695 6205  338
   16] [

[  0   0   0   0   0   0   0   0   0   0 253 759 517  11 128] [0 0 1]
[   0    0    0    0    0    0    0    0    0    4  171  138 2307   22
  366] [1 0 0]
[   0    0    0    0    0    0    0   24  858    1    6    7 1171  171
  858] [1 0 0]
[   0    0    0    0    0    0    0    0    0  343    9    4 1854    4
 2520] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0  366 3114
  102] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   2 364  84  67  91] [0 1 0]
[ 482   64  923 1263  905   17  334  136   17  174  125    2  821 1958
 3041] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0  98  16  70 166] [1 0 0]
[   0    0    0    0    0    0    0    0    0  738  386  280 1974   69
  463] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   0  13 154  35] [0 1 0]
[   0    0 1628 6318  573  111   81   14   17   15  628   17 6319   20
 1114] [0 0 1]
[   0    0    0    0  105 2478    9    4  830   89  280  513   28   65
 3115] [0 0 1]
[   0    0    0    0    0    0  

[  0   0   0   0   2  30 869 586  51 125 869  36   1 152  19] [0 0 1]
[   0    0    0    0    0    0    0 6340   39  322 2606  114   49 4021
    1] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0 115 960 140 208] [1 0 0]
[  0   0   0   0   0   0   0   0   2 645   9   4 406  57 993] [0 0 1]
[  0   0   0   0   0 134  48  26   1  14 331 648 723  17 134] [1 0 0]
[   0    0    0    0    0    0    0    0   63   34 6341 6342  125 1605
    4] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0  58  31  24 162] [1 0 0]
[   0    0    0    0    0    0    0  452    8  467  237 1411 1857 3977
 1193] [1 0 0]
[   0    0    0    0    0    0    1  210  481    5   37   52  158  115
 1938] [1 0 0]
[  0   0   0   0   0   0   0  49 664 470 391  27  39  16  30] [0 1 0]
[   0    0  418  105 4022  246 2550 6343   85  104 6344  270  594 6345
 2420] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0 318  27   1 116   2] [0 1 0]
[  0   0   0   0   0 272 257   9   4 397 254 100 377  11 281] [1 0 0]
[   0    0

  366] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0  60  93 147] [1 0 0]
[   0    0    0    0    0    0  133   58  297   68  999  590   60  402
 3133] [0 1 0]
[   0    0    0    0    0    0   47 1403  251  649  990   47  135  577
 6425] [0 1 0]
[   0    0    0    0    0    0   45  144  189 2617   28   24  400  854
  144] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   2 169 170] [0 0 1]
[   0    0    0    0    0    0    0    0  880  796 2366  122 1990 1023
    1] [0 0 1]
[   0    0    0    0    0    0    0 3654  811 1844 4005  218 6426 6427
 6428] [0 1 0]
[   0    0 1512   57 2618  346 6429  109 6430 1292 1472  494  997  494
  233] [1 0 0]
[   0    0    0    0    0   29   74   34  453 1424   52   74  278    8
  157] [1 0 0]
[   0    0    0    0    0    0  551   12 6431 1155  149 6432  269  508
    6] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0  15  16  56 110  51] [0 1 0]
[   0    0    0    0    0    0    0    0  543  414  126    1 6433 6434
 6435] [1 0 0]
[

   70] [0 1 0]
[   0    0    0    0  784  177 1037   74  196   23  211   29   74  196
   23] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  3 15 27  1 28] [1 0 0]
[   0    0    0    0    0    0  522 2986  525   77   54  788 6475 1918
   69] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0  26 191  58  31  27] [0 1 0]
[  0   0   0   0   0   0   0   0   0 186 100   1  24  56 110] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0   54 3071 6476
   14] [1 0 0]
[   0    0    0    0    0    0    0   30 6477  111  902   78 1329 1181
 1561] [1 0 0]
[   0    0  799 1864 1067  132  281  132  161 3039 4069   46 1124  565
 1067] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0  16 222 123 124] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0   56  103
 4070] [0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1] [0 1 0]
[  0   0   0   0   0   0   1   6  17 144 344   9   4 390 662] [1 0 0]
[   0    0    0    3    6 4071   10  248  408   29 4072 6478   20   35
  312] [1 0 0]
[   0   

   75] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  8  5  1  1 76] [0 1 0]
[   0    0    0    0    0    0    0  235  209   38  154    1 6546  310
 1388] [1 0 0]
[   0    0    0    0    0    0    0    0   62  609    1 3068 1422 6547
  564] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0  23 208 381] [1 0 0]
[   0    0    0    0    0   30  502   43  610 1192   39    1   42    3
  163] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 119   6] [0 1 0]
[   0    0    0    0    0    0    0  110    1 2522  847   43   50   67
   60] [0 1 0]
[   0    0    0    0  629 1335   72    1   11 6548  986 1309  472 6549
  986] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    0 6550    1
  121] [0 1 0]
[   0    0    0    0    0    0 1207  229  972 3619 6551 6552 6553  451
  291] [1 0 0]
[   0    0    0    0    0    0    0    0    0 2083 3914 1898  738    9
  675] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   1   6   7 382  57] [1 0 0]
[   0    0    0    0    0    0  

 6631] [0 0 1]
[   0    0    0    0    0    0    0    0    0 6632   13  238    1   42
  103] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  3 41] [1 0 0]
[   0  520   47 1200 1430  256  256  135 6633 6634  845 2048   31   47
  467] [0 0 1]
[   0    0   54   10    5  192    1 2630  669  248   69   96 1664 2027
 1229] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  219 1566  341  350
 1296] [0 0 1]
[   0    0  195   19   18   44    1  275  109   40   51  453   33  112
 6635] [1 0 0]
[  0   0   0   0   0   0   0   0   0   2 320 406  31 337  39] [0 1 0]
[  0   0   0   0 320   9   4 196   9 439 217 277  31 264 201] [1 0 0]
[   0    0    0    0    0 2146 2268 1238 4131    1   92   64 1154   15
  632] [1 0 0]
[  0   0   0   0   0  73 230  19 144  35 162 140  62 287 118] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  783 1217 1505 3150
   24] [0 1 0]
[   0    0    0    0   96    1 6636  436    1    6  985  133  133   42
  457] [1 0 0]
[   0    0    0    0    0    0  

  177] [0 1 0]
[   0    0    0    0    0   73  963   21  188 3691 2497  426 1188  114
  424] [1 0 0]
[   0    0    0    0    0   34   16    8   76   18 2851   23   33  112
    8] [1 0 0]
[  0 526  18 122 575  17 459 774 877 496  17  15   3  89 469] [1 0 0]
[   0    0    0    0    0    1  129  144 6704 6705    1 1008 6706  835
  326] [1 0 0]
[   0    0    0   12   60  297   39  143  241  142   28   13    7  563
 1187] [1 0 0]
[   0    0    0    0    0    0    0 1114   26  444   14 1232   28 4147
   82] [1 0 0]
[   0    0    0    0    0    0    0    0  720  643  367  551  266  920
 1142] [0 1 0]
[   0    0    0    0    0    0  320    1 4148  113   52    5   37   45
  147] [0 1 0]
[   0    0  205  126  763 2757  325  946    1  316  419    6   54  173
 1281] [1 0 0]
[   0    0    0    0    0    0    0  845  251 1355  422   56  336  298
   56] [0 1 0]
[   0    0    0    0  182   51   57  249   79   13    3  879   41  261
 2520] [1 0 0]
[  0   0   0   0   0   0   0   0  14   1  42 223  29   

[  0   0   0   0   0   0   0  57  11  81  47  81  49 270 343] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0  65 107] [1 0 0]
[   0    0    0    0    0    0    0    0  668   34  104  484  423 4175
  752] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0 70 43  5  1  1] [1 0 0]
[   0    0    0    0    0    0    0    0  262   10 3169  514 2084 1222
 6799] [1 0 0]
[   0    0    0    0    0    0  196  478 1961  590  173  155 1435  289
  266] [1 0 0]
[  0   0   0   0   0   0   0   0   0 393 402 279 188 318 188] [0 1 0]
[   0    0    0    0    0    0    0    0   73  101   34   30   20 2860
   13] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
 6800] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0 562  78  54 336   8] [1 0 0]
[  0   0   0   0   0   0   0   0   0  44 259 202 250   1 289] [1 0 0]
[   0  618  696   17 2232  324   17   69   35   70  279   45   75 3166
   59] [1 0 0]
[   0    0   27   41  254    1    1 6801    5   37  306  852  661  552
  736] [

  469] [1 0 0]
[   0    0    0    0    0    0   24 1214  187    1  191   32  751   12
    6] [1 0 0]
[   0    0    0    0 3529 2643   66  850    4 3979  343   46  360  464
   66] [1 0 0]
[   0    0    0    0    0    0  120  160  246   26   10  478 2868 1019
  144] [1 0 0]
[   0    0    0    0    0    0    0    0    2  309  722 6877  291 1664
 1891] [0 0 1]
[  0   0   0   0   0   0   0   0  23 209   1  16  20  13  53] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0  42 309   2] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 164   2] [0 0 1]
[   0  201   81 1015 3994  185 1070 3032 2471   96  860  419  185  690
 6878] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0 2582  627  109
 1274] [1 0 0]
[   0    0    0    0    0    0  223  217  200 1287   51 1119   23   53
    6] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0 3153  912  912
  912] [0 1 0]
[   0    0    0    0    0    0 1293   86   17   28  438   17  148   84
  406] [1 0 0]
[

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[   0    0    0    0    0    0    0    0 6925   40   10   10 2527  369
    1] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0 6926    6  554
 6927] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    1  155 1269
  106] [0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 6] [1 0 0]
[   0    0    0    5   80  429    1  228    1  498  622  232  753 6928
 6929] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0 3160  989
 3034] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0  15  45 693 239] [1 0 0]
[  0   0   0   0   0  31  64 216 802 168 340 968 151 336 494] [1 0 0]
[   0    0    0    0    0  334  345 4219 2206 1153  139 3482  508   94
   43] [1 0 0]
[   0  434 1325 3195  230    3   18   44   90  171  335 1183  812  337
 1550] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0  123  124
 6930] [0 1 0]
[   0    0    0    0    0    0   27  933 1129  202    3   15   19   17
   27] [1 0 0]
[   0 

  132] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0  477 7030
 4105] [0 0 1]
[  0   0   0   0  18 344  34 225   7 938  48   1 703  48 297] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
 2341] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0   23   26   22 1698
  170] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0 695 127 401 370] [0 1 0]
[   0    0    0    0    0    0   57  339 2132  760   33    1   20   35
    3] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0 3073
  425] [1 0 0]
[   0    0    0    0    0    0    0    0    0   48  262    9  474 1796
 2022] [1 0 0]
[   0    0    0    0    0   65  117   12   19  155 1162  411   24  230
  113] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0  593  415
 1496] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0 312] [0 1 0]
[   0    0    0    0    0    0   27 1707  336  393   76  746  175 1213
 1081] [0 1 0]
[

   25] [1 0 0]
[   0    0    0    2 1629   84  105   58   31  104    9  101  295 1940
  811] [1 0 0]
[  0   0   0   1 228   5  37 144  76  35  12  64   1 171  60] [1 0 0]
[   0    0    0    0    0    0  150  568  174  536 1650 7143  588   40
  154] [1 0 0]
[   0    0    0    0    0    0    0    0  497   26   18   44 1709  409
  270] [0 0 1]
[   0    0    0    0    0    0  601   83  356  762  152   33  112    1
 7144] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0  353  159  972   74
 7145] [0 0 1]
[   0  620   44 1531   81   60  290   17 1812    5  509 3189  643  551
  567] [1 0 0]
[  0   0   0   0   0   0  13  45  15   5 192 208   1  97  28] [1 0 0]
[   0    0   14  287  613   41 1892   47   53  132  204   13   47   42
  126] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0  12 400  17  96 334] [1 0 0]
[   0    0    0    0   20   35  330  856  616   70   64   22   56  471
 4273] [1 0 0]
[   0    0    0    0    0    0    0    0    0    7   72 7146   56 2370
  102] [1 0 0]
[

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 18] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0 960 771   7  11] [1 0 0]
[  0   0   0   0   0  43 105  28  65  16 311 295  60 681   2] [1 0 0]
[   0    0    0    0    0    0    0   89 3219 4095  130   31   46   43
 7185] [1 0 0]
[   0    0    0  368   98  176 7186   75   45  178   14  134    3   33
    1] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0 59 18  1] [0 1 0]
[  0   0   0   0   0   0   0   0   0 152  52 106 101  52 106] [1 0 0]
[  0   0   0   0   0  49 259  11 422 355 117   7  22  10 121] [1 0 0]
[   0    0 1978  291  376   24  259  154    1   86  213    1  393 2620
  926] [0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0   15   66 1418
    1] [1 0 0]
[   0    0    0    0    0    0    0   15    3   17   23  783  400  808
 7187] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0 197] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0 715 648   2 715  49] [0 0 1]


[  0   0   0   0   0   0   0   0   0 156   1 939 253 227 766] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0 1649   63   46    7
   11] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0 3981 7288  222  123
  124] [0 0 1]
[   0    0    0    0    0  488   71  532 7289  503 7290 2265 1849  820
   79] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0  126 3192   25
   22] [0 0 1]
[  0   0   0   0   0   0 171  66  58  42 244 121 115  59 102] [1 0 0]
[   0    0    0    0    0    0    0   44   21    1  205   26 1070 4303
  351] [1 0 0]
[   0    0    0    0 4304 7291    1 1033   59  696 1380   10 7292  712
 2222] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 193  68] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0  61 866 303  19] [1 0 0]
[   0    0    0 3127   68    1  383    5   37   29   51 7293  379  131
   87] [1 0 0]
[   0    0    0    0  902 2653   36  135   61 7294   48  508   17  518
  418] [1 0 0]
[   0    0    0    0    0    1  

[  0   0   0   0   0   0   0  18  27  76  15  45  90 213   8] [1 0 0]
[   0    0    0    0    0    0    0    0    0    2  243 2254   38  159
   10] [1 0 0]
[   0    0    0    0  212    2 1185  289 1092  588  202  395    1  186
  194] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0 267 857 251  42  52] [0 1 0]
[  0   0   0   0   0 182  51 460 718 424 249 157   9   4  18] [1 0 0]
[  0   0   0   0   0   0   0   0   2 107  15  31  67 170 130] [1 0 0]
[   0    0    0    0    0    0    0    0    0   47   29   22  372  701
 7346] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0  23  71 231] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  235    1    3 1081
  388] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0   11 7347
  272] [1 0 0]
[   0    0    0    0    0    0    0  132   64   14 1650  304  335 2010
    6] [1 0 0]
[   0    0    0    0  558  479  148  654  171 1499  479   29    9    4
 3117] [1 0 0]
[  0   0   0   0   0   0   0   0   0  89   6   3

  102] [1 0 0]
[  0   0   0   0   0   0   0 478 547 279 173 155  91 598   8] [1 0 0]
[   0    0    0    0    0    0    0    0  126  256 3238  203  531 1487
 2281] [0 1 0]
[   0    0    0    0    0    0  211  119 2081  263    5   37   52    8
  158] [0 1 0]
[   0    0    0    0    0    0    0    0 1956   51  386  262   28  668
   59] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0 45 28 89 68 15] [1 0 0]
[   0    0    0    0    0   47  250   37    1   52   23   76  426  312
 7420] [1 0 0]
[   0    0    0    0    0    0   18    5    1    1  678   15    3 1145
 2018] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   4  96 513] [1 0 0]
[  0   0   0   0   0   0  23   1  17   5  37 376   7  27  13] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0 15  3] [1 0 0]
[   0    0    0    0    0    0    0    0    0    8  372  434 7421  297
   68] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0 107] [1 0 0]
[   0    0    0    0  151   26   10  273 1262  637  143    8  955  695
 3053] [

 7481] [1 0 0]
[   0    0    0    0  326  386   41  304   57   89 1304  114   18   85
 2793] [1 0 0]
[  53   15    7  107  978 2729  575  114  883 1048 4335  111  132  769
  186] [1 0 0]
[   0    0    0    0  159  126  172  546  994 1612    2  341   36  105
  108] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0  91  35 152  24 889] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  195    2   50   67
 1742] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0 486 372  78 657] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0  34 190] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0   34  414   77    2
 1860] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 190 139] [1 0 0]
[   0    0    0    0  786   97   70   10   55  349    3 7482  850   10
   29] [1 0 0]
[  43 2645  159 1451  241 2619 2179   39   86 1627   94 2015 1616 7483
 2179] [0 1 0]
[   0    0    0    0    0    0 1757  299   69  329   66  220  572 2119
  239] [1 0 0]
[   0    0    0  

    8] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   2  22 448  10 426] [1 0 0]
[   0    0    0  451   38    1   33    1   26   10   38  106 2561   54
  177] [1 0 0]
[   0    0    0    0    0    0   42 1068 7558    1   94  165  179  519
 1098] [0 1 0]
[   0  638   19 7559  127    6 1942   38   98   12   56   33  112  137
 3136] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0  215  748 7560
 2056] [1 0 0]
[   0    0    0 1264 4353  111   14  168   58 7561  232  209   19    1
  139] [1 0 0]
[   0    0    0   51    6  460   32   12  118 2084  788 2225  514 1586
  351] [1 0 0]
[   0    0    0    0    0    0    0    0    0  482    2    8 2320  125
    7] [0 0 1]
[   0    0    0    0    0    0  484  694  593 2324  515  569    1 7562
 7563] [0 0 1]
[  0   0   0   0  10  26 627  45 518 200   7 974   7 279  90] [0 1 0]
[   0    0    0    0    0    0    0  196  122 1304  474  599 2240    1
  281] [0 1 0]
[  0   0   0   0 165 484  83  95  62   8 141  79  17  71 995] [0 1 0]
[

 2705] [0 1 0]
[   0    0    0    0    0 7604    1  150  395   21   79 7605  320 1094
   49] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0 430  99 859 214] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 157  86] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0 1031   19 7606 1031
 7607] [1 0 0]
[  0   0   0   0   0   0   0   0   0  15   3  44   1 145  90] [1 0 0]
[   0    0    0    0    0  312 1629   84 1359   83  172  691   86  295
   67] [1 0 0]
[   0    0    0    0    0    0    0  224   59 7608  352   58  923  794
   79] [1 0 0]
[   0    0    0    0   92  553 2556  298  647 1126 3087 3964 1443   64
 3965] [0 0 1]
[  0   0   0   0   0 299   4 171  49 956 301  19  54  78 306] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0 7609
 1501] [1 0 0]
[  0   0   0   0   0   0   0   8 282 111 910  16 472 334  22] [1 0 0]
[  0   0   0   0   0   0   0   0   0   2 250 509  50  47 130] [0 0 1]
[   0    0    0    0 7610  275  369  489  435  13

   25] [0 0 1]
[   0    0    0    0    0    0    0    0    0 1616    1  491  549  176
  103] [1 0 0]
[   0    0    0    0    0    0    0 3458  649 4369  698  354  116  357
  184] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    7    7    1
 1100] [0 0 1]
[   0    0    0 1967 2232  187   71  223  132   32    8  843  221  770
   10] [0 0 1]
[  0   0   0   0 165  29 149  11 524   1  71 164   2 463 463] [0 0 1]
[  0   0   0   0   0   1 176  62  30  70 183  45 134 343   1] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0   13   67   84
 7658] [1 0 0]
[   0    0    0    0    0    0    0   75  676   31 2205 7659  128 7660
 7661] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   1 134 218  14   8] [1 0 0]
[   0    0    0    0    0    0   30   64  330 1599 2489   17 1419 3119
  188] [0 1 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 25] [0 0 1]
[  0   0   0   0   0   0 104  10  19  93 150 665   3  48  10] [1 0 0]
[   0    0    0    0    0    0    0    0    0 76

  330] [1 0 0]
[   0    0    0    0    0    0 1999 1165  803 3012 1011  771   24 7728
   21] [1 0 0]
[   0    0    0    0    0    0    0 2388   39  435   45   59   88  198
    4] [1 0 0]
[   0    0    0    0    0   49 7729  153  285 4383 1427  188   30 1427
  188] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0  42  41  50  10 775] [1 0 0]
[  0   0   0   0   0   0   0   0  28 109  36 538   7  16 481] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
 7730] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0  63 634  31] [0 0 1]
[  0   0   0   0   0   0   0  18 812 291  16 508 849   7 388] [1 0 0]
[  0   0   0   0   0   0   0   0 100  24 108  79 119   5  37] [0 1 0]
[   0    0    0    0    0    0 1374   68  120 7731 1067 1358  162  146
    3] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[   0    0    0    0    0    0  108   47   56   19 2218 4384 7732 7733
 3380] [1 0 0]
[  0   0   0   0   0   0 201 580 657  19 150 504  54   9  10] [1 0 0]
[   0    

 7848] [1 0 0]
[  0   0   0   0   0   8 102  28  34   8 116  99  62 519 243] [1 0 0]
[   0    0    0    0    0    0   16  140 1726 1221  903   11   56  443
  443] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0 1007  366   60  171
   84] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 164  73] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   0  67  47 159] [0 1 0]
[  0   0   0   0 203   3  49   7  38 270   7  34 439 936 345] [1 0 0]
[   0    0    0    0    0    0    0    0   60 1385  186  765   13   13
    8] [1 0 0]
[  0   0   0   0   0   0  72 104  82 249 926 257   4   7   7] [1 0 0]
[  0   0   0   0   1   5  37 152 218   1   7 230 203   3 187] [1 0 0]
[   0    0    0    0    0    0    0    0   85   38   98    3 3790   54
   10] [1 0 0]
[  0   0   0   0   0   0 441  18   7 237  39  23  18  33 112] [1 0 0]
[   0    0    0    0    0    0    0 1165 2042  123  190   11 3242 1057
  535] [1 0 0]
[   0    0    0    0   12   60  297  174  337 1220    1  568   11

[  0   0   0   0   0   0  35 674  20  40  57  81   6  72  90] [1 0 0]
[   0   45  478   68  453   53  453  181   15   59 1418  756  575  114
 1129] [1 0 0]
[   0    0    0    0    0    0    0    0   11   34  111 1201   19   65
  143] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0  25  22 582] [0 0 1]
[  0   0   0   0   0   0   0 246 215 512 423  75 672   1  22] [1 0 0]
[  0   0   0   0   0   0   0   0  88  84  13  52 106   1 937] [1 0 0]
[   0  362 1728  160  584   27   76  109   26 2596    5  842   12  410
  117] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 290   1   2] [1 0 0]
[  0   0   0   0   0   0   0  24 798  34 191 511  84 172  50] [1 0 0]
[   0    0    0    0    0    0  323   16  203 1229  198    7  253   43
    1] [1 0 0]
[   0    0    0    0    0    0 1115 1050    2 2928 1290  470  799    1
 7963] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   1   6 653  87] [1 0 0]
[   0    0    0    0    0    0   16  134  210   78  179  415   50  161
 7964] [1

   84] [1 0 0]
[   0    0    0    0    0    0    0    0    0 8003  138  610   30 1021
    9] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0  12  58 398 165 309] [0 1 0]
[   0    0    0    0    0    0    0    0  247    1   72  211  111 8004
  336] [1 0 0]
[   0    0    0    0    0    0    0   18  159    1 8005  266  166    8
  652] [1 0 0]
[  0   0   0   0   0   0  40 557   1  22 685 273 672 100 220] [1 0 0]
[   0    0    0    0    0    0  259 1786 1351  390  604 1528  587  772
 4435] [0 1 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0 59 88 35] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0  99  62  42 319] [1 0 0]
[   0    0    0    0 1396 1225  863   12   29   53   47   79 2785   25
  261] [1 0 0]
[  0   0   0   0   0  26  90 565 186 378 196 169 344 389 189] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0  33   1 222 123 124] [0 1 0]
[   0    0    0    0    0   16  252 2668  899  674   46 8006  921  363
 1249] [0 1 0]
[  0   0   0   0   0   0   0   0   0  73  73  73 396 352  56] [0

 3541] [1 0 0]
[   0    0 1915  603  683 8059   43  187  115  603  519   54   17   70
  458] [0 1 0]
[   0    0    0    0    0    0    0    0    0    5    1    1  619   32
 8060] [1 0 0]
[   0    0    0    0    0    0    0    0   65   68 1915  245  155  245
  185] [1 0 0]
[   0    0    0    0    0    0    0    0  799 2948   63   72   11   62
   93] [0 0 1]
[  0   0   0   0   0   0   0   0   0 204 172   9 808 262  28] [1 0 0]
[   0    0    0    0   23   39  533 8061  542  533 8062   61 1163   17
 8063] [1 0 0]
[  0   0   0   0   0   0 815 114 266 202  23 130 765  70 801] [1 0 0]
[   0    0    0    0    0    0    0   12   29 1609  625   48  214  102
 1596] [1 0 0]
[   0    0    0    0    0   62  267 2183 1335  625  201   58   31    7
   11] [1 0 0]
[   0    0 1001   12  400    1   27  205  196 2619 1397   16 1001   77
 1751] [0 1 0]
[   0    0    0    0    0    0    0    0  288  596 1902 1090  595  422
  211] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0   73    1   31   16


 8103] [1 0 0]
[  0   0   0   0   0   0   0   0  28 160  53 496 115  29 160] [1 0 0]
[   0    0    0    0    0    0    0    0   34    1  129    1  453 1916
 1383] [0 0 1]
[   0    0    0    0    0    0  164    9    4  552 8104  255  647 2077
  194] [0 0 1]
[  0   0   0  29   4   5  37   1 340 168   1  11 111 679  19] [1 0 0]
[  0   0   0   0   0   0  34 142 293   1   5  80 426 102 201] [1 0 0]
[   0    0   70 1171   66   24  340    5   80  432    1   65   94   94
   13] [1 0 0]
[  0   0   0   0   0   0   0   0 617 440  99  11  31  34  87] [1 0 0]
[   0    0    0    0    0    0    0    0    0    2  297   68 1138  125
    8] [0 0 1]
[   0    0    0    0   18 1015   87 3271  142   26   66  449   26   20
 1870] [1 0 0]
[   0    0    0    0 1038  175    7  250  855 1038  467  376  450 1278
 2294] [1 0 0]
[  0   0   0   0   0   0 105 559 190 111  41   3  33   1 656] [1 0 0]
[   0    0    0    0    0    2 1164    6  264  201  125  545   75  206
    4] [0 0 1]
[   0    0    0    0    0    0   

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[ 0  0  0  0  0  0  0  0  0  0  0  0 91 67 34] [0 1 0]
[   0    0   53    6  119  180  385 1213  105  559  232  613  176   38
 8190] [1 0 0]
[  0   0   0   0   0   0   0   0   0  70 115  97 134  45 147] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0   83   42   14  191
 1322] [0 1 0]
[  0   0   0   0   0   0   0   0   0 162  12  28   3  13   7] [1 0 0]
[   0    0    0    0    0    0    0    1    5   80 2585  291 3075 1278
 2294] [1 0 0]
[   0    0    0    0  442 2858  789   69  105  559  789    5  192 2197
   76] [1 0 0]
[   0    0    0    0    0    0    0    0    1   36  923  211  318  323
 8191] [1 0 0]
[   0    0    0    0    0  133   41 1225   29  113   97   28  116 8192
  293] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0   62 1200  295 8193
  830] [1 0 0]
[   0    0    0    0    0    0    0    0   55  258  294    3  134 1003
  260] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0 16 35 26] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0

    2] [0 0 1]
[   0    0    0    0    0    0    0    0  397    5  842  378 1637    1
  375] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0   0   0  13   1 214] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0  28  46 665 677] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0   22 8229   88  186
  240] [1 0 0]
[   0    0    0    0    0    0    0 1264   23    1   82    2  246   38
   98] [1 0 0]
[   0    0    0    0    0    0   70    1   48   86 1042 4059  699  114
  815] [0 1 0]
[   0    0    0    0    0    0    0    0   15    3  693  453   16 1155
   27] [1 0 0]
[   0    0    0    0    0    0    0  300  229 1090   34  224  157  371
  427] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   2  91 396  10] [0 0 1]
[   0    0    0    0    0   29   22   74  138  741   12 1058 2123   16
    8] [1 0 0]
[   0    0    0    0  300 8230   50  501   11  229  922   47   34   25
   22] [0 0 1]
[   0    0    0   30  162   88   31 3475   75  432    1  518  200    7
  907] [1 0 0]
[

[  0   0   0   0   0   0   0   0   0   0 199  33   1 238  67] [1 0 0]
[   0    0    0    0    0    0   88   59  158  555 8263   15  158   88
  107] [1 0 0]
[   0    0    0    0    0    0    0 1045  135   64 1649   14 1169 1174
 3309] [0 0 1]
[   0    0    0    0    0    0    0    0    0 1687 8264  557  317 1745
  701] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    0   63 1831
 2622] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0   63   34 1365 1365
 1365] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0    0   30    2
 2004] [0 0 1]
[   0    0    0    0    2    5    1    1 1333  526  345 4465  284   51
 2825] [0 0 1]
[   0    0    0    0    0  136 8265 1042  654   20  429 8266   25   36
  128] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0  18  19 107 949] [1 0 0]
[   0    0    0    0  395 1167   11    7  135   55  258  340   96   29
  674] [1 0 0]
[  0   0   0   0   0   0   0   0  10   1 209  95 134 117 894] [1 0 0]
[   0    0    0 

 1141] [0 0 1]
[   0    0    0    0  226   39  242  181   38  226  689 1211   63  804
 1099] [0 1 0]
[   0    0    0    0    0    0    0 2172  948   51   41    7   29  141
 2939] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0  63 178 137  60] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
 4485] [0 0 1]
[ 0  0  0  0  0  0  0  0  0  0  0  0 11 85 45] [0 1 0]
[   0    0    0    0    0    0    0    0   29 4486   77  733 1525   31
  667] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0  183  190  958
 1695] [1 0 0]
[  0   0   0   0  82  22   1 135 105  26 332  20  26  78 179] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0   48 8397
  585] [0 1 0]
[   0    0    0    0    0    0    0    7 1222  514 1420   41   24   61
 1043] [1 0 0]
[   0    0    0    0    0    0  638 3268   39 8398  214  321   11   22
  539] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0  722 1899 8399
   93] [0 0 1]
[   0    0   98 

    2] [0 1 0]
[   0    0    0    0    0  590  202  260  279 8447   68  148   99   62
  489] [1 0 0]
[  0   0   0   0   0   0   0   0   0   2   8 573  77  39 290] [0 0 1]
[   0    0    2   58   31  404 4491    4  181 4232  418  133   70  376
    1] [0 1 0]
[   0    0    0   89  341    7   58 1765    9    4   86   54   10 1510
  208] [1 0 0]
[  0   0   0   0   0   0   1  52 320 293 146  90 144  35  97] [1 0 0]
[   0    0    0    0    2    1 3081  284 8448   64  757   36  886 8449
 3081] [0 1 0]
[   0    0    0    0    0    0   24  600   19  217  448    6 1880    5
  509] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  123  124 8450 1028
    1] [0 1 0]
[   0    0    0    0    0 2404   30  476   82  726  132   96 2473   47
 1324] [1 0 0]
[  0   0   0   0   0   0   0  16 144 780 189  38  66 836 108] [1 0 0]
[   0    0    0    0    0    0  576  449   61  137  178   21  140  576
 4492] [1 0 0]
[   0    0    0    0    0    0    0    0  336 8451 1025 1475  370  928
  336] [1 0 0]
[

  520] [1 0 0]
[   0    0    0    0    0    0    0    0    0 1568    1    7  299  339
  408] [1 0 0]
[   0    0    0    0    0    0    0    0 1152  178  330  228  487  196
  331] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   0   7  27 313] [0 1 0]
[  0   0   0   0   0   0   0 268 230  19 580   3  15 107   3] [1 0 0]
[   0    0    0    0    0   15   79 1418  346  917    9  513   62   14
  325] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0 8509
 4089] [0 1 0]
[   0    0    0    0    0    1    5   37 1323 2277 4076  111   41   34
  600] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0 1886    1   72
    7] [0 1 0]
[   0    0    0    0    0   79   55   14    3    1 1005    1   42  688
 1613] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   5  37  19 658] [1 0 0]
[   0    0    0    0    0    0    0    2 2230   35   24   17  232  215
   56] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
 1783] [1 0 0]
[

 8541] [0 1 0]
[   0    0    0    0    0   12   36 4486   77   61  203  373  248 4484
 1221] [1 0 0]
[   0    0    0    0    0  471 1844 4407 4408 2162 2039 2044 3178  747
 1259] [0 1 0]
[   0    0    0    0    0    0    0    0  145  140 8542   21   14  196
   11] [1 0 0]
[  0   0   0   0   0   0   0   0  33   1 260  66 311  61  64] [1 0 0]
[   0 8543    6  200   26   10   20  179  522  505  696  178  522    6
 2294] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0 564 465 291 897] [0 1 0]
[  0   0   0   0   0   0   0   0 249   6 187 200  24 492   1] [0 1 0]
[   0    0    0    0    0    1 1589  679  228  279    5   37   24  152
    1] [1 0 0]
[   1    5   37  263    4   35  140  420  371 1604 2168  263  989 1156
  501] [1 0 0]
[  0   0   0   0   0   0 849  84 321  71 150 614 385  78   1] [1 0 0]
[   0    0    0    0  334  345   86   31  334  345 4382   65 8544   59
  523] [1 0 0]
[   0    0    0    0    0    0    2  182 8545   20  223   71   72  260
  239] [1 0 0]
[   0    0    0  

  153] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   8 537 546 345 447] [0 1 0]
[   0    0    0    7  230  117   18  326 1398 2521   41 3607   66 8622
 1584] [1 0 0]
[   0    0    0    0    0    0    0   73   48  841 1981    9    4  148
 8623] [0 1 0]
[   0    0    0    0    0    0    0    0 8624  628  161  283  156 1180
 2679] [1 0 0]
[   0    0    0    0    0    0    0    0    0   23  337  116 1533    1
  383] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0  15  43 190] [1 0 0]
[  0   0   0   0   0   0   0   0   0  30  20 434   7  20 178] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0  553 1252  549   38
    1] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0    0    2 4380
  243] [1 0 0]
[   0    0    0    0  268  174    1 1132  180   22   81  174  328 8625
  753] [1 0 0]
[  0   0   0   0   0   0 306 135 341 270   7  36  63  11  34] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0 172] [1 0 0]
[   0    0    0    0    0    0   

    4] [1 0 0]
[   0    0    0    0    0   38  546  193 2459  176 8680   93 2094   19
 2094] [1 0 0]
[   0    0    0    0    0    0   26 1652   65  580    7  394   86    9
  299] [1 0 0]
[   0    0    0   18   11 1091  187 2796  781  215  240 8681    5   37
  673] [1 0 0]
[   0    0    0    0    0    1  129 8682  269  645    4 8683  863   19
  357] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0 651  71  95   6 693] [1 0 0]
[   0    0    0    0    0    0   38   20 8684 1004  303   17  284  167
    2] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  300   34    1  699
 2001] [1 0 0]
[   0    0    0    0    0    0    0  206    9    4  759   11   34 3289
 1731] [0 0 1]
[   0    0    0    0    0    0    0    0   25  182 8685  701  298   64
 8686] [0 1 0]
[   0    0    0    0    0  739   40   10   42  386  208   91  304 1720
 8687] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   2  84  12 406 435] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0   49 8688   76


  721] [0 0 1]
[   0    0    0    0    0    0    0    3   10   11 1934 1935 1451  215
   10] [0 1 0]
[   0    0    0    0    0 8758  333 1109 1109 1109   63   11  371  427
  813] [0 0 1]
[   0    0    0    0    1   11 8759  577   77  256  341  350   11    3
 8760] [1 0 0]
[   0    2    8  379  131  207    5 4482 4013 2599    8 2003 2285    7
 8761] [0 0 1]
[   0    0    0    0    0 1318   39 1366 4286  610  634  455 2233   69
  765] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    2 2247    1    7
 2581] [0 0 1]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  1 36] [0 1 0]
[   0    0    0    0 1761  450 3734    1   86  576  424 1409  129  107
 1955] [1 0 0]
[   0    0    0    0    0    0    0    0 2389    3  255 2389    3   12
  107] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0 1250
  543] [0 0 1]
[   0    0    0    0  265  137  210 4461    1  286 8762 1163 8763   30
  137] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0  13  20 178  25 278] [0 1 0]


    9] [1 0 0]
[   0    0    0   26 4520 4521  361  176  812  291  487 1067   78   26
  176] [1 0 0]
[   0    0    0    0    0    0    0    0    0 1362    5    1    1  619
   52] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0 1856   74  637
  513] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0 618  89 278 360] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0  15 974 167  15] [1 0 0]
[   0    0    0    0    0    0  211  232 2375  792   99  273  145  453
    8] [1 0 0]
[  0   0   0   0   0   0  13   3 144 158   1  51   4 254  36] [1 0 0]
[   0    0    0    0    0    0   12  152   50  282   20   49  434    1
 8836] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  411  634  538   64
 1154] [0 1 0]
[   0    0    0    0    0    0    0  351 1532   69  120 1997 4296  233
   10] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0 1171    1 1091    5
   80] [1 0 0]
[   0    0    0    0    0    0 1224    1   71   72  206  104 1000    1
 1073] [0 0 1]
[

   85] [0 1 0]
[  0   0   0   0   0  16   8  18   5   1   1  72  15  88 399] [1 0 0]
[   0    0    0    0    0    0    0    0 1318 1016   83  839   54 8886
 1416] [1 0 0]
[  0   0   0   0   0   0   0   0 212  39 393  39 186 265   2] [0 1 0]
[   0    0    0    0    0    0    0    0  323   15  540 1270   43   76
  588] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 882 433   7] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0 249   6 113  52 106] [0 1 0]
[   0    0    0    0    0    0    0    0    2  256  147 1678  411  399
   41] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0 3595 2952 3604
 2624] [0 1 0]
[   0    0    0    0    0    0  526  238 2588 1245   21  690  474 1284
 1997] [1 0 0]
[   0    0    0    0  102    1  145    1  237   22 1847   32    3  284
 1301] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[   0    0    0   34    9    4  941  230  893 4519  962 8887  204 3791
 2013] [1 0 0]
[  0   0   0   0   0   0   0   0 121   1 216 302 499 378  35] [

  239] [1 0 0]
[   0    0    0    0    0  690  594 1066    1   96   26 1537  557  987
   76] [1 0 0]
[   0    0    0    0    0    0  318  159 2441  451   68   39    1  131
   87] [0 1 0]
[   0    0  136   82   56  421   11  127  881  285 3391 1680  357  184
 4387] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0   98    2   93
 8935] [0 0 1]
[  0   0   0   0 346 181  89 100  72   1 130 183 235  59 100] [1 0 0]
[   0    0    0  721   10 1329 1565   20  218  225   10  886  223  948
 2115] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0   58 2943
 3249] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0 1302
 2116] [0 1 0]
[   0    0    0    0    0    0    0    0  255 8936 8937   65  154    9
    4] [1 0 0]
[   0    0    0    0    0    0    0    0    0   24    1  151   77 1563
  523] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    1  228 1514 8938
 8939] [0 0 1]
[   0    0    0    0    0    0    0   13   84  246  122

 1252] [0 1 0]
[   0    0    0    0    0    0    0  134  104    2    8  564 3894  274
  671] [0 1 0]
[   0    0    0    0    0    0 8975  101   23   30  257   74  470  177
  588] [1 0 0]
[   0    0    0    0    0   69 3213  135   29   22  553 8976 8977  151
  155] [1 0 0]
[   0    0    0    0  412  174 3661  136 1136 1393  569    1   99  285
 2659] [1 0 0]
[   0    0    0    0    0 1345    3   55   14  223  113  739    1 1257
 1931] [1 0 0]
[  0   0   0   0   0   0   0   0  18 120  35  19   5  37   1] [1 0 0]
[   0    0    0    0    0    0    0   76 2061   48   30 8978  108  369
  616] [1 0 0]
[   0    0    0    0    0    0   36  761   22   63 1200 1430  256  972
    2] [0 0 1]
[   0    0    0    0    0    0    0    0    0   31   30 8979  489   90
 8980] [0 1 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0 34 54 66] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   1 712 282  29   1] [1 0 0]
[   0    0    0    0   22  392  189   36  748    4  210   88  570 1734
 3615] [1 0 0]
[  0   0   0   0

[  0   0   0   0   0   0   0   0   0   0   0   0   0  82 988] [0 1 0]
[  26  332    1  968  319   14   66 2941   47  506  271    7  214   17
 9082] [1 0 0]
[  0   0   0   0   0   0   0   0   0  10 331 595 736  78 175] [1 0 0]
[  0   0   0   0   0   0   0   0  15 167 158   5  80   1  36] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0  12 824  72 104   2] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0 2323 2814 9083 4524
 1179] [1 0 0]
[  0   0   0   0   0   0   0   0   0  15   3 249   9   4 469] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0 2198
   10] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 618  70] [1 0 0]
[   0    0    0    0    0    0    0    0    0   96 9084   64  220 1447
 2639] [1 0 0]
[   0    0    0    0    0    3  438    6    1 3230 3179  923  352 1684
 1299] [1 0 0]
[   0    0    0    0    0    0  614 1039  774  903 2409 2665  640  751
   19] [0 1 0]
[   0    0    0    0    0    0    0    0    0  280   25  598  26

  365] [0 1 0]
[   0    0    0    0    0    0   16  120  446  783    8  122  143  456
 9127] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0  199 1370 3755
 3756] [1 0 0]
[   0    0    0    0    0   22  373   36   16   27    1    7  129 1282
   19] [0 0 1]
[   0    0    0    0    0    0   12   16  752  691    5  981  656 1051
 1011] [1 0 0]
[   0    0    0    0    0    0   11   24  270   93   54   10   43  514
 1073] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0 317 301   3] [1 0 0]
[   0    0    0    0    0    0    0  529 3996   19   77  422 9128 9129
 2243] [0 0 1]
[   0    0    0    0   87  116   18  105   27   81  183  202   12 3322
  335] [1 0 0]
[   0    0    0    0    0    0    0  281 1155  130   64    1 1765    9
    4] [1 0 0]
[  0   0   0   0   0 212   1 113   5  37 110  65  42  68   8] [1 0 0]
[ 299   69 1571  512  423   17  294    3    1 2462 4062 4063 4513 1885
  273] [1 0 0]
[   0    0    0    0    0    0    0  206  356   49 9131  409 3193  831


 1063] [1 0 0]
[   0    0    0    0    0    0    0    0   63  229  574    1  129 4469
 4538] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0    0    0    2 3187
   27] [0 1 0]
[   0    0    0    0    0    0    0    0    1  113 3205   24    5   37
   52] [1 0 0]
[   0    0    0    0    0    0    0   73   45 1902  839  161  206   25
   36] [0 0 1]
[   0    0    0    0    0    0    0    0    0    0 4539  482  157   33
    1] [1 0 0]
[  0   0   0   0  95 296  96 206 127 128  50  60 447 961  74] [1 0 0]
[   0    0 9177 3583  113  279 1774    9    4   32 1814  597   86  318
    2] [0 0 1]
[   0    0    0    0    0  171 2988  150   26 1448   40  292 4177  720
  643] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0   63   64  153
 1441] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   0  20 315 552] [0 1 0]
[   0    0    0    0    0   21 1044  252 1354   24 9178   14  132   95
  327] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0  126 3192   25


  205] [0 0 1]
[   0    0    0    0    0    0    0    0    0  313  108  242  286  359
 4531] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0  12  43 127 296 271] [0 1 0]
[   0    0    0    2   38   10 3286   96 3297 2658 9213  399   41  336
  593] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 903   6] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0 46  2 91] [0 0 1]
[   0    0    0    0    0   13   11    6   54   10  138   59 1896  229
   25] [1 0 0]
[   0    0    0    0    0    0    0   18  188 1710  138  331  111    3
   34] [1 0 0]
[   0    0   20  760  565    6  382  183   40   33    1  121  541   23
 2253] [1 0 0]
[   0    0    0    0  253  395 1502  771  326 1384   41   12  326  117
  338] [1 0 0]
[   0    0    0    0    0    0 1234    1  209  296 9214  158    9    3
 1150] [1 0 0]
[   0    0    0    0    0    0 2503   13   84  292   60 4529 1237   84
    7] [1 0 0]
[   0    0    0    0  222   61  126  763  173   12   40  636  109 1175
  182] [1 0 0]
[  0   0   0   0

 9254] [1 0 0]
[   0    0    0    0    2  229  537   77 3207   24   38  272 9255    2
 9256] [0 0 1]
[   0    0  202  279    7 2570  202  279    6   18  874  444  530  119
  327] [1 0 0]
[   0    0    0    0    0    0    0    0 1736   15    3  317    8   16
    1] [1 0 0]
[   0    0    0    0    0    0    0  472   11   47   54    9  397 1275
  233] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0    0  111 1097
 1127] [1 0 0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0 268 109] [1 0 0]
[   0    0    0    0  937  177  153  555 3249  434   21  325 1062  748
   19] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  417   62    6 9257
 9258] [1 0 0]
[   0    0    0    0    0  513 3586 9259  311 1912  247   78  175   72
 1528] [0 0 1]
[   0    0    0    0    0    0  365  101 1516   84  294   83  810  172
   92] [1 0 0]
[   0    0    0    0 2223  150 2273 9260   17  142  670 1273 9261   61
 2688] [1 0 0]
[   0    0    0    0    0    0    0    0  722  165  369

    8] [0 1 0]
[   0    0    0 3091  416 1400 1236  858  371  427  792   57   64 1781
  406] [1 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0 16  8 39 67] [0 1 0]
[   0    0    0  212  575  114  266 2410  354 2963 2964 3453 2201   18
   44] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0  807 9341  114 3668
    1] [0 1 0]
[  0   0   0 212   1 619 349   5  80  58  31   1 619  72 226] [1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2] [0 0 1]
[   0    0    0    0    0  543 9342  219   27  807  725  148   99  394
  672] [1 0 0]
[   0    0    0    0    0    0   28   88 1040   29   51   18   44  270
 2295] [0 1 0]
[   0    0    0    0    0    0    0    0    0    0 1211  291 1670   48
   18] [0 1 0]
[  0   0   0   0   0   0   0   0   0   0 195   2 197 832  22] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0   0   0 317 510 752] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0   30  216 9343
 1196] [0 1 0]
[   0    0    0    0    0    0    0    0    0  185  140    1  491  975
 1763] 

 9406] [1 0 0]
[  0   0   0   0   0   0   0   0   0   2 364 243  49 224 365] [0 0 1]
[  0   0   0   0   0   0   0   0   0   0 442  19  49  27 220] [1 0 0]
[   0    0 9407   20  263  369  834    9    4    8   64  424  194  206
   96] [0 0 1]
[   0    0    0    0    0    0  108   14  196   42   13  928 9408  335
   51] [1 0 0]
[   0    0    0    0    0    0    1  391   95    6  320   27   51 1945
  884] [1 0 0]
[   0    0    0    0    0   13   10  681   23 1176   82   23   47   89
   45] [1 0 0]
[   0    0    0    0  149   48  201   81 1310   13  848   13    7   92
  456] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0  105   38 9409   85
 9410] [1 0 0]
[   0    0    0 1249   11 2534 3777 2990 2219    8   24 4354 2875  893
  224] [0 1 0]
[   0    0    0    0    0    0    0    0    0 4259   11  259 1042  241
  366] [1 0 0]
[   0    0    0    0    0    0    0    0    0    0    0  817   12 9411
  888] [0 0 1]
[  0   0   0   0   0   0   0   0   0 162 666 166 380 183   2] [0 0 1]
[

Saving our features and classes data

In [23]:
from numpy import savetxt
savetxt('features.csv',features,delimiter=',')
savetxt('classes.csv',classes,delimiter=',')

0
0  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46, 125,...
1  [[0, 0, 1], [1, 0, 0], [1, 0, 0], [1, 0, 0], [...